### STATE FARM ASSOCIATES FUNDS TRUST GROWTH FUND
### STATE FARM GROWTH FUND.

-- THEY HOLD THOSE NOTES WITH " NO CERTIFICATE OF OCCUPANCY " 
-- AND PRESENT THEM TO THE BANKS / FINANCIAL INDUSTRY TO GET A LOAN.


TICKER: STFGX
	SEC FILE NUMBER: 811-01519
	SERIES: S000002055
	LEI: 25490064REEQMGE0GC29
	CIN: C000005410
	CIK: 93715
						
##### STFGX
Item C.16. 		Brokers.
			Morgan Stanley & Co. LLC
			SEC: 008-68191 
			CRD: 000149777 [8209]
			21,307.100000000000 
	
ITEM C.17 
			MORGAN STANLEY & CO LLC 
			SEC: 008-68191 
			CRD: 000149777 [8209]
			32,718,613.440000000000 
THURSDAY, NOVEMBER 25, 2021. . . . . . . . . . . . . . . . . . . . . . . . . . .[0168]

		FROM: 	ADMIN@HUTCHMENT.COM

		SENT:	<LZUCKER@MSKYLINE.COM>, <SLASKOWITZ@INGRAMLLP.COM>, 

						<SLASKOWITZ@MSKYLINE.COM>, <ASHLEY.HUMPHRIES@WILSONELSER.COM>,

						<MSRBSUPPORT@MSRB.ORG>, <ALEX.KRESS@WILSONELSER.COM>,

						<BBREIF@BLOOMBERG.NET>, <MHARVEY13@BLOOMBERG.NET>, 

						<COLIN.BROOKS@MORGANSTANLEY.COM>, <ICEGLOBALNETWORK-INFO@ICE.COM>,

						<ICEINDICES@ICE.COM>, <ADMINISTRATOR@MSKYLINE.COM>, 

						<COMPLIANCE@T3TRADING.COM>.

						

				DOCKET 309 AND DOCKET 379 IN THE MESSAGE BODY

					"ENTIRE LOT" LEASES AND RENTS TRANSFERRED TO STATE FARM

					ALL SIX PROPERTIES WITH "NO CERTITFICATE OF OCCUPANCY"

											IN THE YEAR 2020

											AND IN THE YEAR 2022

																   

		https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=19MVPFXy0G0QvnmRLGpYIQ==

		

		RECEIVED NYSCEF: 08/09/2020

																   

		https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=572E8gahZUO1KFthrfiyFQ==

		RECEIVED NYSCEF: 08/10/2020

		

Thursday, November 25, 2021. . . . . . . . . . . . . . . . . . . . . . . . . . .[0170]

		FROM: 	BO.DINCER@YAHOO.COM

		TO:		<SLASKOWITZ@INGRAMLLP.COM>, <SLASKOWITZ@INGRAMLLP.COM>,

				<SERVICE@ETRADE.COM>, <LZUCKER@MSKYLINE.COM>, <CHAIR@SEC.GOV>,

				<FIDELITY.INVESTMENTS@MAIL.FIDELITY.COM>

				

STATE FARM. . .  . .  . .  . .  . . . . . . . . . . . . . . . . . . . . . . . . [0171]



	DOCKET 385 

	https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=K9sgXcweC7esRoSPO8MNtA==

	RECEIVED NYSCEF: 08/10/2020

	

	FROM:		B-DINCER66@OUTLOOK.COM

	SUBJECT:	RE: STATE FARM

			

	"... I INFORMED YOUR CLIENT OF THIS MATERIAL INFORMATION..."

		

	DOCKET 420

	https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=Xjn0/e1NcBADqRc_PLUS_g11P4g==



JULY 21, 2020. . . . .  . .  . .  . . . . . . . . . . . . . . . . . . . . . . . [0178]

--- THERE'S A CAMERA POINTED INTO MY APARTMENT AND AT MY LAPTOP, AND THEY MUST HAVE

	MISSED THE SPOT WHERE I CAUGHT THEM IN THE ACT EARLIER.



JULY 21, 2020. . . . .  . .  . .  . . . . . . . . . . . . . . . . . . . . . . . [0181]

	--- AS STATED.

	THEY WILL DO " ANYTHING " TO AVOID PROSECUTION IN THIS RESPECT.
STATE FARM ASSOCIATES' FUNDS TRUST. . . . . . . . . . . . . . . . . . . . . . . . . . . . . [0183]

[FORM N-8F] 2021-09-21

" Application for Deregistration of Certain Registered Investment Companies. "

https://www.sec.gov/Archives/edgar/data/0000093715/000119312521278180/d222043dn8f.htm



THIS POSTHASTE MERGER IS THE ESSENCE OF GROSS NEGLIGENCE, WHICH IS UNDERSTOOD

IN THE LOSSES OF ITS INVESTORS, AS THE OLD ONES HAVE NO KNOWLEDGE OF ANY MATARIALLY

SUBSTANTIVE MATTERS, AND NOR TO THE NEW INVESTORS WHO BLINDLY INVESTED THEIR CAPITAL

INTO THE NEW ADVISOR. CIK FILER 1519523

															

	Reason fund is applying to deregister. . . . . . . . . . . . . . . . . . . .[0184]		

			/s/ David Moore.

			Assistant Secretary

			ONE STATE FARM PLAZA

			BLOOMINGTON, IL, 61710						(309) 766-1908										

	

	Name, address and telephone number of  entity. . . . . . . . . . . . . . . .[0184]

			State Farm Investment Management Corp.

			One State Farm Plaza

			Bloomington, Illinois 61710-0001			(309) 766-1908

	

	Name and address of each principal underwriter of the fund. . . . . . . . . [0185]

			State Farm VP Management Corp.

			One State Farm Plaza

			Bloomington, Illinois 61710-0001

	

	Does the fund have any outstanding debts or any other liabilities . . . . . [0186]

	

*** GROSS NEGLIGENCE IN MANAGING THE ASSETS AND MERGER . . . . . . . . . . . . .[0187]

https://www.sec.gov/Archives/edgar/data/0000093715/000119312521278180/d222043dn8f.htm



******  ACCOUNTING FOR THE $250.00 MIN. INVESTED IS FURTHERANCE TO THE GROSS NEGLIGENCE.

	>> ANY SOFT DOLLAR AGREEMENTS BETWEEN THE INVESTMENT ADVISER & ITS BROKERS WOULD

		ONLY ADD TO WHAT IS UNDERSTOOD AND REPORTED AS FOLLOWS.

		

			(i)  	Legal expenses: 									$240,000

			(ii) 	Accounting expenses: 			 	  		    	$  9,000

			(iiI) 	Proxy Solicitation and Tabulation					$170,000

					Prospectus Supplements and Regulatory Filings		$ 62,500

					Directors fees										$431,000

										
---

# A SOURCE OF INCOME FOR A GUARANTEE TO A BANK???

DOCKET 309 AND DOCKET 379 IN THE MESSAGE BODY
"ENTIRE LOT" LEASES AND RENTS TRANSFERRED TO STATE FARM

ALL SIX PROPERTIES WITH "NO CERTITFICATE OF OCCUPANCY"
IN THE YEAR 2020
AND IN THE YEAR 2022
																	   
https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=19MVPFXy0G0QvnmRLGpYIQ==
		
RECEIVED NYSCEF: 08/09/2020
																	   
https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=572E8gahZUO1KFthrfiyFQ==
RECEIVED NYSCEF: 08/10/2020
			
### [DECEMBER 18TH, 2021] NOTICE TO MORGAN STANLEY AND STATE FARM 
		
### AUDIT AND OPINION OF PRICE WATERHOUSE COOPERS
###### Section 3.6 TAX AND LIEN PAYMENTS BY "STATE FARM" 



THERE ARE NO CERTIFICATES OF OCCUPANCY ON FILE FOR THE ADDRESSES TRASNFERRED AND USED AS GUARANTEE TO :STATE FARM:
-- IN ORDER TO OBTAIN A $6,000,000.00 LOAN, TRANSFERRED THE RIGHTS OF THE LEASES, RENTS, AND TAX LIABILITIES IN DOING SO.


	
https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=19MVPFXy0G0QvnmRLGpYIQ==
	
https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=ze6a1KA9akRV9TGfXXJT/g==
	
https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=bVk8sIt7n3kGwHqebPg0fw==
	
https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=wTG2YD2PqXuxmoKqFiESrw==
	
https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=au8qh7Dn66hrVmJ9DX_PLUS_bdg==
	
https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=/yhElCiKJ0BGv2DF/MOn4g==
	
https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=gcMSDaFzm0ynPeXZKSHgLQ==

# WILSON-ELSER-DICKER-LASKOWITZ-MOV
ELSER-AND-DICKER

Wed, Jun 3, 2020, 2:20 PM        RECEIVED NYSCEF: 08/09/2020 
 https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=TxAa7cNVIHKtnJU/ni/zvg==
            21 JULY 2020    NYSCEF DOC. NO. 53             RECEIVED NYSCEF:     07/21/2020

                    "...REPRESENTATIVES SHOULD BE DISBARRED..."
https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=LMUE9g_PLUS_k6vCmKgfCSJEzuQ==

https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=TxAa7cNVIHKtnJU/ni/zvg==

https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=PWFQc/WFihoyIKwEunaalQ==

          

           
#### CERTITIICATES OF OCCUPANCY FOR THE RENTS AND LEASES TRANSFERRED TO STATE FARM

https://a810-bisweb.nyc.gov/bisweb/cosbylocationservlet?requestid=3&allbin=1077252
														   
NYSCEF DOC. NO. 230 																					 08-04-2020
https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=JjKiWNUTBeipcESQfFiwVQ==
	
NYSCEF DOC. NO. 388 																					 08-10-2020
https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=ZOCFS3HH2UeHQe8j2tXJoQ==

																													   		
113 REAR SULLIVAN STREET, BIN CODE 1077254
https://a810-bisweb.nyc.gov/bisweb/cosbylocationservlet?requestid=3&allbin=1077254
		
																													   
115 REAR SULLIVAN STREET, BIN CODE 1077256
https://a810-bisweb.nyc.gov/bisweb/cosbylocationservlet?requestid=3&allbin=1077256
	
																													   	
117 SULLIVAN STREET, BIN CODE 1007779
https://a810-bisweb.nyc.gov/bisweb/cosbylocationservlet?requestid=3&allbin=1007779

		
BIS CERTIFICATES OF OCCUPANCY
https://a810-dobnow.nyc.gov/publish/index.html#!/search
		
																													   
111 REAR SULLIVAN STREET, BIN CODE 1077252
- NO CERTIFICATE OF OCCUPANCY 									03-03-2022
- NO CERTIFICATE OF OCCUPANCY 									08-10-2020
	
NYSCEF DOC. NO. 388 										08-10-2020
https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=ZOCFS3HH2UeHQe8j2tXJoQ==
                

               


https://github.com/BSCPGROUPHOLDINGSLLC/ELSER-AND-DICKER/pull/11

![image](https://user-images.githubusercontent.com/70865813/167291117-656e2a28-7591-4ecf-b5e0-bf5e4d58b678.png)

---
                            STFGX
                            Date    Close/Last    Adjusted Close

                            11/10/2021    121.17    121.17
                            11/11/2021    120.77    120.77
                            11/12/2021    121.48    121.48
                                                        __________________________
                                                        11/15/2021    121.34    121.34
                                                        11/16/2021    121.6    121.6
                                                        11/17/2021    121.52    121.52
                                                        11/18/2021    121.87    121.87
                                                        11/19/2021    121.69    121.69
                                                        11/22/2021    121.64    121.64
                                                        11/23/2021    121.79    121.79
                                                        11/24/2021    121.85    121.85
                                                        11/26/2021    119.44    119.44
                                                        11/29/2021    120.48    120.48
                                                        11/30/2021    118.5    118.5
                                                        12/1/2021    117.78    117.78
                                                        12/2/2021    118.95    118.95
                                                        12/3/2021    118.46    118.46
                                                        12/6/2021    119.95    119.95
                                                        12/7/2021    121.89    121.89
                                                        12/8/2021    122.51    122.51
                                                        12/9/2021    121.99    121.99
                                                        12/10/2021    123.25    123.25
                                                        12/13/2021    122.76    122.76
                                                        12/14/2021    122.16    122.16
                                                        12/15/2021    124.36    124.36
                                                        12/16/2021    123.55    123.55
                                                        12/17/2021    121.93    121.93

                        INSIDER TRADING [DECEMBER 18TH, 2021]. . . . . . . . . . . . . . . . . . . . . .[0212]

![image](https://user-images.githubusercontent.com/70865813/167291170-f30a3492-9be0-4b43-b958-aa909c839c60.png)


                        --------------------------------------------------------------------------------------
                                                                                    __________________________
                                                                                    12/20/2021    120.72    120.72
                                                                                    12/21/2021    106.35    106.35
                                                                                    12/22/2021    107.39    107.39
                                                                                    12/23/2021    108.08    108.08
                                                                                    12/27/2021    109.52    109.52
                                                                                    12/28/2021    109.57    109.57
                                                                                    12/29/2021    109.82    109.82
                                                                                    12/30/2021    109.55    109.55
                                                                                    12/31/2021    109.48    109.48
---





        ------- Original Message -------
        On Friday, May 6th, 2022 at 10:59 PM, BD <bondstrt@protonmail.com> wrote:



            21 JULY 2020    NYSCEF DOC. NO. 53             RECEIVED NYSCEF:     07/21/2020

                    "...REPRESENTATIVES SHOULD BE DISBARRED..."

                https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=LMUE9g_PLUS_k6vCmKgfCSJEzuQ==

                https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=TxAa7cNVIHKtnJU/ni/zvg==






            ------- Original Message -------
            On Friday, May 6th, 2022 at 10:50 PM, BD <bondstrt@protonmail.com> wrote:


                FROM 11-30-2021 THOUGH 03-31-2022


                                $852,029,498.38 

                 
                                FOR ALL FOUR OF THE TICKERS UNDER THE FORMER UMBRELLA OF 93715
                                -- MERGED INTO A LARGER BODY OF RISK UNDER THE UMBRELLA 1516523
                                -- UNDER THE ADVISEMENT AND OMISSION OF ITS COUNSELORS, CONTINUE TO
                                -- HEMORRHAGE ITS CAPITAL AT THE EXPENSE OF ITS INVESTORS WITHOUT
                                -- ANY PUBLIC DISCLOSURE, OR ESTOPPEL BY FINRA PERMIT FOR THEM TO
                                -- CONTINUE TO FUNCTION WITHOUT ANY "TRUE" SPECIALIST TO HANDLE
                                -- THEIR AFFAIRS, DEMONSTRABLY AS SEEN IN THE PERFORMANCE OF THE
                                -- FUND.

                        ----------------------------------------------------------------------------------
                            STFGX
                            Date    Close/Last    Adjusted Close

                            11/10/2021    121.17    121.17
                            11/11/2021    120.77    120.77
                            11/12/2021    121.48    121.48
                                                        __________________________
                                                        11/15/2021    121.34    121.34
                                                        11/16/2021    121.6    121.6
                                                        11/17/2021    121.52    121.52
                                                        11/18/2021    121.87    121.87
                                                        11/19/2021    121.69    121.69
                                                        11/22/2021    121.64    121.64
                                                        11/23/2021    121.79    121.79
                                                        11/24/2021    121.85    121.85
                                                        11/26/2021    119.44    119.44
                                                        11/29/2021    120.48    120.48
                                                        11/30/2021    118.5    118.5
                                                        12/1/2021    117.78    117.78
                                                        12/2/2021    118.95    118.95
                                                        12/3/2021    118.46    118.46
                                                        12/6/2021    119.95    119.95
                                                        12/7/2021    121.89    121.89
                                                        12/8/2021    122.51    122.51
                                                        12/9/2021    121.99    121.99
                                                        12/10/2021    123.25    123.25
                                                        12/13/2021    122.76    122.76
                                                        12/14/2021    122.16    122.16
                                                        12/15/2021    124.36    124.36
                                                        12/16/2021    123.55    123.55
                                                        12/17/2021    121.93    121.93

                        INSIDER TRADING [DECEMBER 18TH, 2021]. . . . . . . . . . . . . . . . . . . . . .[0212]
                        --------------------------------------------------------------------------------------
                                                                                    __________________________
                                                                                    12/20/2021    120.72    120.72
                                                                                    12/21/2021    106.35    106.35
                                                                                    12/22/2021    107.39    107.39
                                                                                    12/23/2021    108.08    108.08
                                                                                    12/27/2021    109.52    109.52
                                                                                    12/28/2021    109.57    109.57
                                                                                    12/29/2021    109.82    109.82
                                                                                    12/30/2021    109.55    109.55
                                                                                    12/31/2021    109.48    109.48
                    __________________________________________________________________________________________



                -------- Forwarded Message --------
                Subject:	***LOAN 50074 annexed IN 153974/2020 State Farm and Sullivan Properties LP. [ receipt ]
                Date:	Fri, 6 May 2022 22:43:02 -0500
                From:	B D2022 <ms60710444266@yahoo.com>
                To:	Andrew Keller [FINRA] <akeller106@bloomberg.net>, Andrew Korb [FINRA] <akorb1@bloomberg.net>, Austin McCrary [FINRA] <amccrary@bloomberg.net>, ASHLEY MEAD [FINRA] <amead11@bloomberg.net>, Andrew Smith [FINRA] <asmith1151@bloomberg.net>, Anthony Walker [FINRA] <awalker231@bloomberg.net>, Cassandra Kirk [FINRA] <ckirk21@bloomberg.net>, Chris Gursky [FINRA] <csgursky@bloomberg.net>, Dian Zhu [FINRA] <dian.zhu@finra.org>, FINRA Corporate Notification <finracorporatenotification@finra.org>, FINRA Product Management <finraproductmanagement@finra.org>, finrawebmaster@finra.org <finrawebmaster@finra.org>, FINRA CAT Helpdesk <help@finracat.com>, hesham.ibrahim@finra.org, iard@finra.org, Jessica.Brach@finra.org, Josephine.Vella@finra.org <Josephine.Vella@finra.org>, John Sagan [FINRA] <jsagan8@bloomberg.net>, Joshua Wong [FINRA] <jwong554@bloomberg.net>, Kimberly Berry [FINRA] <k28826@bloomberg.net>, Kenneth Thompson [FINRA] <kthompson84@bloomberg.net>, michelle.ong@finra.org, nancy.condon@finra.org, pfrdsupport@finra.org, Finra Webmaster <postmaster@finra.org>, ray.pellecchia@finra.org, rosalyn.marcus@finra.org <rosalyn.marcus@finra.org>, Rosinna Rivera [FINRA] <rrivera88@bloomberg.net>, TRACE Data Services <tracedataservices@finra.org>, Finra Webmaster <webmaster@finra.org>, Yana Siegel <yana.siegel@wilsonelser.com>, WILLIAM BEHR <william.behr@wilsonelser.com>, Urvashi Sinha <urvashi.sinha@wilsonelser.com>, Thomas R. Manisero <thomas.manisero@wilsonelser.com>, Suzanne S. Swanson <suzanne.swanson@wilsonelser.com>, Stephen J. Barrett <stephen.barrett@wilsonelser.com>, Stacey L. Seltzer <stacey.seltzer@wilsonelser.com>, Sean Wagner <sean.wagner@wilsonelser.com>, Roger R. Gottilla <roger.gottilla@wilsonelser.com>, Ricki Roer <ricki.roer@wilsonelser.com>, Ricki Roer <ricki.roer@wilsonanddicker.com>, ricki.raared@wilsonsdickers.com <ricki.raared@wilsonsdickers.com>, Randyc.wilson@usdoj.gov <Randyc.wilson@usdoj.gov>, patricia.wik@wilsonelser.com, meghan.rigney@wilsonelser.com, Lori Semlies <lori.semlies@wilsonelser.com>, Lois K. Ottombrino <lois.ottombrino@wilsonelser.com>, Lauren M. Zink <lauren.zink@wilsonelser.com>, Kathleen A. Mullins <kathleen.mullins@wilsonelser.com>, jwilson578@bloomberg.net, judy.selmeci@wilsonelser.com, Jennifer L. Sciales <jennifer.sciales@wilsonelser.com>, Jennifer M. Provost <jennifer.provost@wilsonelser.com>, info@wilsonelser.com, Hannah.King@WILSONELSER.COM, grace.song@wilsonelser.com, erin.zecca@wilsonelser.com, ellyn.wilder@wilsonelser.com, elizabeth.scoditti@wilsonelser.com, Debra Tama <debra.tama@wilsonelser.com>, Daniel F. Flores <daniel.flores@wilsonelser.com>, curt.schlom@wilsonelser.com, craig.hunter@wilsonelser.com, craig.brinker@wilsonelser.com, Corrine Shea <corrine.shea@wilsonelser.com>, carole.nimaroff@wilsonelser.com, aviva.stein@wilsonelser.com, Ashley V. Humphries <ashley.humphries@wilsonelser.com>, Angelique Sabia-Candero <angelique.sabia-candero@wilsonelser.com>, angel.vitiello@wilsonelser.com, Andrea Shiffman <andrea.shiffman@wilsonelser.com>, Amy Hanrahan <amy.hanrahan@wilsonelser.com>, alex.kress@wilsonelser.com, ALDEN 00066govtIdx WILSON <alden.wilson@maine.gov>, Alan Rubin <alan.rubin@wilsonelser.com>, terrance.ludwig@statefarm.com, replacementprogram@statefarm.com, rebecca.coyle@statefarm.com <rebecca.coyle@statefarm.com>, PHIL SUPPLE <phil.supple.hid9@statefarm.com>, PAUL.SMITH@STATEFARM.COM, Nicole Bowyer <nicole.bowyer@statefarm.com>, State Farm <mutualfunds@statefarm.com>, MIKE.CARTER.HUSL@STATEFARM.COM, JOSE.MONK@STATEFARM.COM, dick.luedke.h2hj@statefarm.com, David Moore <david.moore.ct95@statefarm.com>, brian.hodgson.nyz6@statefarm.com <brian.hodgson.nyz6@statefarm.com>
                CC:	Alisa Maksimova [FRB-NY] <Alisa.Maksimova@ny.frb.org>, Solis, Anita <anita.solis@chi.frb.org>, Cynthia.H.Francis@frb.gov, dallas-reserve-mgmt@dal.frb.org <dallas-reserve-mgmt@dal.frb.org>, Mielke, Evan P <evan.p.mielke@chi.frb.org>, general.info@ny.frb.com <general.info@ny.frb.com>, general.info@ny.frb.org <general.info@ny.frb.org>, kenneth.j.fraser@frb.gov, media@chi.frb.org <media@chi.frb.org>, ny.public.information@ny.frb.org, ny.reserves@ny.frb.org <ny.reserves@ny.frb.com>, ny.reserves@ny.frb.org <ny.reserves@ny.frb.org>, nyreporting.forms@ny.frb.org <nyreporting.forms@ny.frb.org>, oighotline@frb.gov <oighotline@frb.gov>, reserves@chi.frb.org <reserves@chi.frb.org>, PRIYA.RAGHURAM@MORGANSTANLEY.COM, MSHY15@MORGANSTANLEY.COM, mscampusrecruiting@morganstanley.com, mediainquiries@morganstanley.com, kerri.saperstein@morganstanley.com <kerri.saperstein@morganstanley.com>, john.varriano@morganstanley.com <john.varriano@morganstanley.com>, jmorgan274@bloomberg.net, Jessica.Colpani@morganstanley.com, JAMES GORMAN [MORGAN STANLEY] <james.gorman@morganstanley.com>, colin.brooks@morganstanley.com <colin.brooks@morganstanley.com>, alex.zuluaga@ey.com <alex.zuluaga@ey.com>, david.brown1@ey.com <david.brown1@ey.com>, Deborah M Jones <Deborah.Jones@ey.com>, info@ey.com <info@ey.com>, jacqueline.kelley@ey.com <jacqueline.kelley@ey.com>, karim.anani@ey.com <karim.anani@ey.com>, kevin.klimara@ey.com <kevin.klimara@ey.com>, lee.henderson@ey.com <lee.henderson@ey.com>, mark.schwartz1@ey.com <mark.schwartz1@ey.com>, rachel.gerring@ey.com <rachel.gerring@ey.com>, slaskowitz@inngramllp.com <slaskowitz@ingramllp.com>


                To whom this may concern.

                LOAN DOCKETS WERE NOTARIZED AND ANNEXED IN NYSCEF 153974/2020

                . . . . . . . . . . . . . . . . [0254]

                DOCKET 270-- ATTACHED... --- RECEIPT

                - NO WONDER THEY ACCEPT $2.00 AND HAD TO HIRE A LARGER FIRM...

                https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=Uavl5NRQV4YHKqWUf8fyVQ==     

                                   

                ACRIS REPORT: transfer and assignment of RENTS and LEASES [ income used as guarantee ]

                    https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=19MVPFXy0G0QvnmRLGpYIQ==


                of the Sarbanes-Oxley Act of 2002
                    https://github.com/BSCPGROUPHOLDINGSLLC/ELSER-AND-DICKER/pull/27

                 FILER: 93715

                    https://www.sec.gov/Archives/edgar/data/0000093715/000119312520200810/d913497dex99cert.htm
                    https://www.sec.gov/Archives/edgar/data/0000093715/000119312520200810/d913497dex99906cert.htm


                ______________________________________________________________________________________________
                    
                    TOTAL LOSSES SUFFERED ON THE BASIS OF THE REPORT FILED BY THE COMPLIANCE OFFICER
                    OF STATE FARM VP. MANAGEMENT CORP ON 11-30-2021 THROUGH THE END OF Q1, 2022
                    
                    
                       STFGX        STFBX        SFITX        SFBDX

                        COMBINED LOSSES

                FROM 11-30-2021 THOUGH 03-31-2022


                                $852,029,498.38 

                 
                                FOR ALL FOUR OF THE TICKERS UNDER THE FORMER UMBRELLA OF 93715
                                -- MERGED INTO A LARGER BODY OF RISK UNDER THE UMBRELLA 1516523
                                -- UNDER THE ADVISEMENT AND OMISSION OF ITS COUNSELORS, CONTINUE TO
                                -- HEMORRHAGE ITS CAPITAL AT THE EXPENSE OF ITS INVESTORS WITHOUT
                                -- ANY PUBLIC DISCLOSURE, OR ESTOPPEL BY FINRA PERMIT FOR THEM TO
                                -- CONTINUE TO FUNCTION WITHOUT ANY "TRUE" SPECIALIST TO HANDLE
                                -- THEIR AFFAIRS, DEMONSTRABLY AS SEEN IN THE PERFORMANCE OF THE
                                -- FUND.

                        ----------------------------------------------------------------------------------
                            STFGX
                            Date    Close/Last    Adjusted Close

                            11/10/2021    121.17    121.17
                            11/11/2021    120.77    120.77
                            11/12/2021    121.48    121.48
                                                        __________________________
                                                        11/15/2021    121.34    121.34
                                                        11/16/2021    121.6    121.6
                                                        11/17/2021    121.52    121.52
                                                        11/18/2021    121.87    121.87
                                                        11/19/2021    121.69    121.69
                                                        11/22/2021    121.64    121.64
                                                        11/23/2021    121.79    121.79
                                                        11/24/2021    121.85    121.85
                                                        11/26/2021    119.44    119.44
                                                        11/29/2021    120.48    120.48
                                                        11/30/2021    118.5    118.5
                                                        12/1/2021    117.78    117.78
                                                        12/2/2021    118.95    118.95
                                                        12/3/2021    118.46    118.46
                                                        12/6/2021    119.95    119.95
                                                        12/7/2021    121.89    121.89
                                                        12/8/2021    122.51    122.51
                                                        12/9/2021    121.99    121.99
                                                        12/10/2021    123.25    123.25
                                                        12/13/2021    122.76    122.76
                                                        12/14/2021    122.16    122.16
                                                        12/15/2021    124.36    124.36
                                                        12/16/2021    123.55    123.55
                                                        12/17/2021    121.93    121.93

                        INSIDER TRADING [DECEMBER 18TH, 2021]. . . . . . . . . . . . . . . . . . . . . .[0212]
                        --------------------------------------------------------------------------------------
                                                                                    __________________________
                                                                                    12/20/2021    120.72    120.72
                                                                                    12/21/2021    106.35    106.35
                                                                                    12/22/2021    107.39    107.39
                                                                                    12/23/2021    108.08    108.08
                                                                                    12/27/2021    109.52    109.52
                                                                                    12/28/2021    109.57    109.57
                                                                                    12/29/2021    109.82    109.82
                                                                                    12/30/2021    109.55    109.55
                                                                                    12/31/2021    109.48    109.48
                    __________________________________________________________________________________________

                       

                    MAY 11, 2020
                    
                        "STATE FARM LIFE INSURANCE COMPANY"
                        BY ITS MANAGING MEMBER
                            -------------------------------
                            STATE FARM REALTY MORTGAGE LLC
                            -------------------------------
                            https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=Xjn0/e1NcBADqRc_PLUS_g11P4g==
                           
                           
                    RECEIVED NYSCEF: 08/11/2020
                        AUG  9, 2020
                            RE: STATE FARM.                DOCKET 398
                            https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=n_PLUS_CvSQR36fqPKko6L47FFQ==
                           
                    
                        AUG 10, 2020
                            LETTER FROM COUNSELORS.     DOCKET 399
                                                        >>> "STATE FARM REALTY INSURANCE LLC" <<<
                            https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=D9Td7IfWXyajw1tBNCFb9g==
                                        I AM UNFAMILIAR WITH >>> "STATE FARM REALTY INSURANCE LLC"



                FY 2020
                    8/9/2020
                    https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=19MVPFXy0G0QvnmRLGpYIQ==
                    NO CERTIFICATE OF OCCUPANCY FILED ON AUGUST 9TH, 2020
                    
                    8/8/2020
                    https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=ZOCFS3HH2UeHQe8j2tXJoQ==
                    NO CERTIFICATE OF OCCUPANCY FILED ON AUGUST 10TH, 2020



                SO WAS THIS.

                I.    THEY MONITORED MY LAPTOP FROM OUTSIDE OF MY APARTMENT.
                    - ON A 24 HOUR BASIS, RECORDED MY EVERY STEP AND MOTION.           
                      https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=c3iexOlBwsgc1lnMJ2_PLUS_AqQ==
                    
                      ASHLEY HUMPHRIES, OF WILSON & DICKER.
                               
                      " ... PLEASE CHECK THE SECURITY TAPES .. "
                      https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=HbnFLHB3tyjhEWAYb6mOPw==
                 
                      https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=YvkihzM1cwANtAvbUwWX_PLUS_g==


                    II.    VIDEOTAPED ME "INSIDE OF MY APARTMENT".
                      https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=UZsCx4RNLy/6V9gf1BkpTQ==


                    III. DISTRIBUTED VIDEOS OF MYSELF IN MY APARTMENT -- THE INTERIOR.
                      https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=YGRsoOyDJuc93MrOnwh5Jw==

                               
                      https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=84wdx4RhX5LEi0sISXetBw==


                    IV. ATTACHED VIDEO OF MYSELF DRILLING INSIDE OF MY APARTMENT.
                      https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=5uMb/ORklCen4NaSEt6oFg==

                               
                    V.    ATTACHED VIDEO OF MYSELF HAMMERING INSIDE OF MY APARTMENT.
                      https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=C4X_PLUS_6_PLUS_kgBxoElZyFgKxGEQ==

                    VI.    THEY ALSO ANNEX RECEIPTS TO HELP BUY THEMSELVES MORE TIME AND TO DISTRACT
                        THE JUDGE/ CLERK AND INSTEAD OF DEALING WITH THEIR TAX-EVASIONS AND ILLEGAL CONDUCT...

                --- CANVAS NEW NEIGHBORHOODS WITHOUT REPRESENTING THE RECEIPTS FOR TAXES PAID IN THE PRIOR 15-YEARS...
                      https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=Uavl5NRQV4YHKqWUf8fyVQ==
                               
                    VII. ALSO WILL SWEAR IN THEIR AFFIDAVITS THAT GO ON FOR PAGES THAT THEY HAVE NO INVOLVEMENT.
                        - HAVE ALSO MONITORED ME FROM THE CORRIDOR, AND THROUGH MY DOOR.
                        - BY ALL OF THE ATTORNEYS, COUNSELORS, AND STAFF OF SULLIVAN PROPERTIES, LP.
                       
                        VIII.    HAVE ALSO ANNEXED AND SWORE UNDER OATH THEY SAW ME
                        https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=PWFQc/WFihoyIKwEunaalQ==
                       
                                        "... BANGING ON A RADIATOR ... "
                                       
                        https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=oz2nfEu9a94Y3U5/kpIt5g==
                                       
                        IX. ALSO HAVE ANNEXED THEY "HOSTED" MY VIDEOS ON THE INTERNET --               

                        -- USING ONE OF THEIR OWN TENANTS AS THE VIDEOGRAPHER..\NO I DONT KNOW TO SPELL THAT I THOUGHT MICROSOFT DID THAT ANYWAYS...

                       
                        https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=PWFQc/WFihoyIKwEunaalQ==
                       

                NO CERTIFICATE OF OCCUPANCY IN FY 2020.

                    https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=ZOCFS3HH2UeHQe8j2tXJoQ==



                CERTIFICATION

                Pursuant to Section 906

                of the Sarbanes-Oxley Act of 2002


                combined CERTIFICATES of OCCUPANCY for all buildings attached as of FY 2022.

                   SOMEWHERE ON PAGE 800 OF THE UNREGISTERED SECURITY ( THE COMBINED  AND RE-STATED PROSPECTUS ) WHICH I ALSO ANNEXED IN THE MATTER OF NYSCEF   153974/2020.

                    https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=ze6a1KA9akRV9TGfXXJT/g==

                    https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=bVk8sIt7n3kGwHqebPg0fw==


                    https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=wTG2YD2PqXuxmoKqFiESrw==


                    https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=au8qh7Dn66hrVmJ9DX_PLUS_bdg==


                    https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=/yhElCiKJ0BGv2DF/MOn4g==


                    https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=gcMSDaFzm0ynPeXZKSHgLQ==


                THEY ALSO ANNEX MY RECEIPT TO HELP BUY THEMSELVES MORE TIME AND TO DISTRACT
                        THE JUDGE, CLERK AND INSTEAD OF DEALING WITH THEIR TAX-EVASIONS AND ILLEGAL CONDUCT.


                HERE YOU GO!


                 260 	EXHIBIT(S)  - 1  (Motion #001)	Laskowitz, S.	Processed
                6.24.2020 email	Filed: 08/04/2020	Confirmation Notice
                 	Received: 08/04/2020	 
                 261 	EXHIBIT(S)  - 2  (Motion #001)	Laskowitz, S.	Processed
                6.25.2020 email	Filed: 08/04/2020	Confirmation Notice
                 	Received: 08/04/2020	 
                 262 	EXHIBIT(S)  - 3  (Motion #001)	Laskowitz, S.	Processed
                6.27.2020 email	Filed: 08/04/2020	Confirmation Notice
                 	Received: 08/04/2020	 
                 263 	EXHIBIT(S)  - 4  (Motion #001)	Laskowitz, S.	Processed
                6.27.2020 email	Filed: 08/04/2020	Confirmation Notice
                 	Received: 08/04/2020	 
                 264 	EXHIBIT(S)  - 5  (Motion #001)	Laskowitz, S.	Processed
                6.27.2020 email	Filed: 08/04/2020	Confirmation Notice
                 	Received: 08/04/2020	 
                 265 	EXHIBIT(S)  - 6  (Motion #001)	Laskowitz, S.	Processed
                6.28.2020 email	Filed: 08/04/2020	Confirmation Notice
                 	Received: 08/04/2020	 
                 266 	EXHIBIT(S)  - 7  (Motion #001)	Laskowitz, S.	Processed
                6.29.2020 email	Filed: 08/04/2020	Confirmation Notice
                 	Received: 08/04/2020	 
                 267 	EXHIBIT(S)  - 8  (Motion #001)	Laskowitz, S.	Processed
                6.30.2020 email	Filed: 08/04/2020	Confirmation Notice
                 	Received: 08/04/2020	 
                 268 	EXHIBIT(S)  - 9  (Motion #001)	Laskowitz, S.	Processed
                Note from Defendant	Filed: 08/04/2020	Confirmation Notice
                 	Received: 08/04/2020	 
                 269 	EXHIBIT(S)  - 10  (Motion #001)	Laskowitz, S.	Processed
                7.2.2020 email	Filed: 08/04/2020	Confirmation Notice
                 	Received: 08/04/2020	 
                 270 	EXHIBIT(S)  - 11  (Motion #001)	Laskowitz, S.	Processed
                7.5.2020 email	Filed: 08/04/2020	Confirmation Notice
                 	Received: 08/04/2020	 
                 271 	EXHIBIT(S)  - 12  (Motion #001)	Laskowitz, S.	Processed
                7.3.2020 email	Filed: 08/04/2020	Confirmation Notice
                 	Received: 08/04/2020	 
                 272 	EXHIBIT(S)  - 13  (Motion #001)	Laskowitz, S.	Processed
                7.6.2020 email	Filed: 08/04/2020	Confirmation Notice
                 	Received: 08/04/2020	 
                 273 	EXHIBIT(S)  - 14  (Motion #001)	Laskowitz, S.	Processed
                7.8.2020 email	Filed: 08/04/2020	Confirmation Notice
                 	Received: 08/04/2020	 
                 274 	EXHIBIT(S)  - 15  (Motion #001)	Laskowitz, S.	Processed
                7.9.2020 email	Filed: 08/04/2020	Confirmation Notice
                 	Received: 08/04/2020	 


                P.S.....


                Has the FDIC checked on Century 21 downtown at the Register booth... to see if that is accurate?
                           





On Tue, Apr 26, 2022, 10:28 PM Bo Dincer <bdincer66@icloud.com> wrote:


    https://open.spotify.com/playlist/1D0U7r06A1auzZCOgUUiQY?si=RXNJjH9yTGKZG0Z5-KsCjg

    I think we beyond 1.5 billion for years x-POST tax avoidance in the public eye, but let’s wait and see what they carve out of BRK-B for comparison. 

    AAPL vs. AAPL is equally weighted, just like the blueberries in casino. Hence, no NYSCEF on this email; just ISDA…

    /BD
    I asked one question Ricki.. “ .. is that all of them .. “

    Then, no further questions. Thank you r letters and annexed in the docket 153974/2020 .. you belong in jail for aiding and abetting tax evasion. 

    Goodnight. 💤 the past, when it’s annexed in Supreme Court, I will read it. So annexed for you is the truth… which untirbately just cost the north of 1 billion in losses at the casual work of your counselors @wilsonDicker or whatever Elon musk thinks they are worth. 

    -0. Which is a number, depending on what brain child spends his life thinking about that. Zero, is zero. 
    .bd

    You like inquiries now Zucker??
    That’s a cool billion and then some. I warned you about that 30yr right??
    In email 8 billion at risk. 


    Loan 50074. 
    Begin forwarded message:

>     From: Bo Dincer <bdincer66@icloud.com>
>     Date: April 26, 2022 at 10:05:14 PM EDT
>     To: edi.civil.rights.division@irs.gov, eca_press@state.gov, teschmann@mskyline.com, 18pctdvo@nypd.org, 18pctyco@nypd.org, cbrooks7@bloomberg.net, 10pctdvo@nypd.org, "Bloomberg L.P." <bbrief@bloomberg.net>, 1pctdvo@nypd.org, 1pctyco@nypd.org, 23pctdvo@nypd.com, iceglobalnetwork-info@ice.com, 23pctyco@nypd.org, ksaperstein2@bloomberg.net, dcaoletters@sec.gov, JPMCinvestorrelations@jpmchase.com, 10pctyco@nypd.org, BD <bondstrt@protonmail.com>, Chair <chair@sec.gov>, Tennesse <sbarchenger@tennessean.com>, Newyork <newyork@sec.gov>, MSRB <msrbsupport@msrb.org>, MSKYLINE <ANNE@thehighlandpartners.com>, BBO 121 <ms60710444266@yahoo.com>, dallas-reserve-mgmt@dal.frb.org, ashley.humphrie@wilsonelser.com, GSAMOnlineRequest@gs.com, blaw.content@bloomberg.net, matthew.chase@lw.com, anthony.sicoli@bnymellon.com, marc.jaffe@lw.com, ofac_feedback@treasury.gov, dion.gaspard@nypd.org, rosalyn.marcus@finra.org, legalasst@mskyline.com, rebecca.coyle@statefarm.com, garrett.marquis@bnymellon.com, ted.banner@bnymellon.com, CHICAGO@sec.gov, TEDHERMANSON@northmarq.com, amount@bressler.com, asksipc@sipc.org, efoia@fdic.gov, electronicfilings@ftc.gov, gs@gs.com, infor@solowresidential.com, LZUCKER@mskyline.com, mshyld@bloomberg.net, newsoffice@mit.edu, oca@sec.gov, privacypolicy@related.com, shareholderproposals@sec.gov, slaskowitz@mskyline.com, tips@insider.com, tips@latimes.com, tips@nytimes.com, tips@vibe.com, wmckenzie@nycourts.gov, FTC ANTITRUST <antitrust@ftc.gov>, Brooklyn Tap House <tips@nypost.com>, CRC FTC REPORTS <crcmessages@ftc.gov>, CS TEAM <Activations@hutchmen.com>, BRIAN HODGSON <BRIAN.HODGSON.NYZ6@statefarm.com>, BO DINCER <bo.dincer@yahoo.com>, Debra Tama <debra.tama@wilsonelser.com>, Dian Zhu <dian.zhu@finra.org>, FOX ROTHSCHILD <JROSE@foxrothschild.com>, Paul Regan <legal@mskyline.com>, Ricki Roer <ricki.roer@wilsonelser.com>, Shari Laskowitz <slaskowitz@ingramllp.com>, Stephen O'Connell <sgo2107@adcu.columbia.edu>, Alan Morrison <ajm157@columbia.edu>, Alan Andreini <aandreini@fortress.com>, UNITED ARTISTS MUSIC <investorrelations@umusic.com>, UNIVERSAL EDITORIAL <investmentnews@editorial.investmentnews.com>, WILLIAM BEHR <william.behr@wilsonelser.com>, ZUCKER ORGANIZATION <jgiamboi@mskyline.com>, Bressler Info <INFO@bressler.com>, Finra Webmaster <webmaster@finra.org>, Goldman Sachs <briefings@gs.com>, JAMES GORMAN <james.gorman@morganstanley.com>, Joseph Giamboi <joseph.giamboi@brooklaw.edu>, LA TIMES NEWSLETTERS <newsletters@latimes.com>, Lee Bollinger <bollinger@columbia.edu>, Lee Bollinger <officeofthepresident@columbia.edu>, Lori Semlies <lori.semlies@wilsonelser.com>, MATT HARVEY <mharvey13@bloomberg.net>, MATT LOWE <mlowe@fdic.gov>, MIKE DANILACK <MIKE.DANILACK@us.pwc.com>, Amy Hanrahan <amy.hanrahan@wilsonelser.com>, Alan Rubin <alan.rubin@wilsonelser.com>, PAM OLSON <PAM.OLSON@us.pwc.com>, PETER MERILL <PETER.MERILL@us.pwc.com>, "Lauren M. Zink" <lauren.zink@wilsonelser.com>, executive_education@mailsvc.sloan.mit.edu, "Ashley V. Humphries" <ashley.humphries@wilsonelser.com>, "Roger R. Gottilla" <roger.gottilla@wilsonelser.com>, ainfo@buildings.nyc.gov, "Jennifer M. Provost" <jennifer.provost@wilsonelser.com>, "Thomas R. Manisero" <thomas.manisero@wilsonelser.com>, "Kathleen A. Mullins" <kathleen.mullins@wilsonelser.com>, skysthelimit@theconcierge.info, foia@eeoc.gov
>     Cc: info@ohysiciansmutual.com, physiciansmutual@physiciansmutual.com, info@ohysiciansmutual.com, wmckenzie@nycourts.gov, espnfrontrow@espn.com
>     Subject: Fwd: 101 STFGX par no look 1516523 CIK Filer ex-post 900$ million in losses.
>
>     ﻿
>
>
>     /BD
>
>
>     Begin forwarded message:
>
>>     From: Bo Dincer <bdincer66@icloud.com>
>>     Date: April 26, 2022 at 8:25:25 PM EDT
>>     To: edi.civil.rights.division@irs.gov, eca_press@state.gov, teschmann@mskyline.com, 18pctdvo@nypd.org, 18pctyco@nypd.org, cbrooks7@bloomberg.net, 10pctdvo@nypd.org, "Bloomberg L.P." <bbrief@bloomberg.net>, 1pctdvo@nypd.org, 1pctyco@nypd.org, 23pctdvo@nypd.com, iceglobalnetwork-info@ice.com, 23pctyco@nypd.org, ksaperstein2@bloomberg.net, dcaoletters@sec.gov, JPMCinvestorrelations@jpmchase.com, 10pctyco@nypd.org, BD <bondstrt@protonmail.com>, Chair <chair@sec.gov>, Tennesse <sbarchenger@tennessean.com>, Newyork <newyork@sec.gov>, MSRB <msrbsupport@msrb.org>, MSKYLINE <ANNE@thehighlandpartners.com>, BBO 121 <ms60710444266@yahoo.com>, dallas-reserve-mgmt@dal.frb.org, ashley.humphrie@wilsonelser.com, GSAMOnlineRequest@gs.com, blaw.content@bloomberg.net, matthew.chase@lw.com, anthony.sicoli@bnymellon.com, marc.jaffe@lw.com, ofac_feedback@treasury.gov, dion.gaspard@nypd.org, rosalyn.marcus@finra.org, legalasst@mskyline.com, rebecca.coyle@statefarm.com, garrett.marquis@bnymellon.com, ted.banner@bnymellon.com, CHICAGO@sec.gov, TEDHERMANSON@northmarq.com, amount@bressler.com, asksipc@sipc.org, efoia@fdic.gov, electronicfilings@ftc.gov, gs@gs.com, infor@solowresidential.com, LZUCKER@mskyline.com, mshyld@bloomberg.net, newsoffice@mit.edu, oca@sec.gov, privacypolicy@related.com, shareholderproposals@sec.gov, slaskowitz@mskyline.com, tips@insider.com, tips@latimes.com, tips@nytimes.com, tips@vibe.com, wmckenzie@nycourts.gov, FTC ANTITRUST <antitrust@ftc.gov>, Brooklyn Tap House <tips@nypost.com>, CRC FTC REPORTS <crcmessages@ftc.gov>, CS TEAM <Activations@hutchmen.com>, BRIAN HODGSON <BRIAN.HODGSON.NYZ6@statefarm.com>, BO DINCER <bo.dincer@yahoo.com>, Debra Tama <debra.tama@wilsonelser.com>, Dian Zhu <dian.zhu@finra.org>, FOX ROTHSCHILD <JROSE@foxrothschild.com>, Paul Regan <legal@mskyline.com>, Ricki Roer <ricki.roer@wilsonelser.com>, Shari Laskowitz <slaskowitz@ingramllp.com>, Stephen O'Connell <sgo2107@adcu.columbia.edu>, Alan Morrison <ajm157@columbia.edu>, Alan Andreini <aandreini@fortress.com>, UNITED ARTISTS MUSIC <investorrelations@umusic.com>, UNIVERSAL EDITORIAL <investmentnews@editorial.investmentnews.com>, WILLIAM BEHR <william.behr@wilsonelser.com>, ZUCKER ORGANIZATION <jgiamboi@mskyline.com>, Bressler Info <INFO@bressler.com>, Finra Webmaster <webmaster@finra.org>, Goldman Sachs <briefings@gs.com>, JAMES GORMAN <james.gorman@morganstanley.com>, Joseph Giamboi <joseph.giamboi@brooklaw.edu>, LA TIMES NEWSLETTERS <newsletters@latimes.com>, Lee Bollinger <bollinger@columbia.edu>, Lee Bollinger <officeofthepresident@columbia.edu>, Lori Semlies <lori.semlies@wilsonelser.com>, MATT HARVEY <mharvey13@bloomberg.net>, MATT LOWE <mlowe@fdic.gov>, MIKE DANILACK <MIKE.DANILACK@us.pwc.com>, Amy Hanrahan <amy.hanrahan@wilsonelser.com>, Alan Rubin <alan.rubin@wilsonelser.com>, PAM OLSON <PAM.OLSON@us.pwc.com>, PETER MERILL <PETER.MERILL@us.pwc.com>, "Lauren M. Zink" <lauren.zink@wilsonelser.com>, executive_education@mailsvc.sloan.mit.edu, "Ashley V. Humphries" <ashley.humphries@wilsonelser.com>, "Roger R. Gottilla" <roger.gottilla@wilsonelser.com>, ainfo@buildings.nyc.gov, "Jennifer M. Provost" <jennifer.provost@wilsonelser.com>, "Thomas R. Manisero" <thomas.manisero@wilsonelser.com>, "Kathleen A. Mullins" <kathleen.mullins@wilsonelser.com>, skysthelimit@theconcierge.info, foia@eeoc.gov, LZUCKER@mskyline.com, citimod1@bloomberg.net, mshy2@bloomberg.net, general.info@ny.frb.org
>>     Cc: espnfrontrow@espn.com, bo.dincer@yahoo.com
>>     Subject: Fwd: 101 STFGX par no look
>>
>>     ﻿
>>
>>
>>     /BD
>>
>>
>>     Begin forwarded message:
>>
>>>     From: Bo Dincer <bo.dincer@yahoo.com>
>>>     Date: April 26, 2022 at 8:23:43 PM EDT
>>>     To: Baris Dincer <bdincer66@icloud.com>
>>>     Subject: Fw: 101 STFGX par no look
>>>     Reply-To: "bo.dincer@yahoo.com" <bo.dincer@yahoo.com>
>>>
>>>     ﻿
>>>
>>>     Sent from Yahoo Mail on Android
>>>
>>>         ----- Forwarded Message -----
>>>         From: "Bo Dincer" <bo.dincer@yahoo.com>
>>>         To: "Baris Dincer" <bdincer66@icloud.com>, "Bo Dincer" <bo.dincer@yahoo.com>, "Bo Dincer" <bondstrt007@gmail.com>, "tips@insider.com" <tips@insider.com>, "tips@latimes.com" <tips@latimes.com>, "tips@vibe.com" <tips@vibe.com>, "Citrus Diner" <tips@gothamist.com>, "American Bar Association" <abanews@americanbar.org>, "4audit@bloomberg.net" <4audit@bloomberg.net>, "Solowresidential Info" <info@solowresidential.com>, "investor@annaly.com" <investor@annaly.com>, "media.relations@kcc.com" <media.relations@kcc.com>, "KEVIN ROCK" <krock5@bloomberg.net>, "Dow Jones" <wsjprosupport@dowjones.com>, "Dow Jones" <pronewsletter@dowjones.com>, "Newyork" <newyork@sec.gov>, "**External ICE Help Desk" <icehelpdesk@ice.com>, "Bill Cassese (ICE BONDS SECURITIES)" <bcassese19@bloomberg.net>, "to-icengx@ice.com" <to-icengx@ice.com>, "iceimsupport@theice.com" <iceimsupport@theice.com>, "isda@isda.org" <isda@isda.org>, "isdaeurope@isda.org" <isdaeurope@isda.org>, "engineering@spglobal.com" <engineering@spglobal.com>, "aaron wood" <aaron_wood@sandp.com>, "Alan Andreini" <aandreini@fortress.com>, "Angel R. Vitiello" <angel.vitiello@wilsonelser.com>, "Ashley V. Humphries" <ashley.humphries@wilsonelser.com>, "ipadhelp@nypost.com" <ipadhelp@nypost.com>, "iphonehelp@nypost.com" <iphonehelp@nypost.com>, "FDIC Public Information" <publicinfo@fdic.gov>, "investorrelations@umusic.com" <investorrelations@umusic.com>
>>>         Cc: "espnfrontrow@espn.com" <espnfrontrow@espn.com>, "newyork@cravath.com" <newyork@cravath.com>, "Charity Navigator" <admin@charitynavigator.org>, "iceglobalnetwork-info@ice.com" <iceglobalnetwork-info@ice.com>, "BMO InvestorLine" <hr.notifications@bmo.com>, "bofamarkets@bofa.com" <bofamarkets@bofa.com>, "jpmcinvestorrelations@jpmchase.com" <jpmcinvestorrelations@jpmchase.com>, "jpminvestorrelations@jpmchase.com" <jpminvestorrelations@jpmchase.com>, "Bloomberg L.P." <bbrief@bloomberg.net>, "blaw.content@bloomberg.net" <blaw.content@bloomberg.net>, "blawre@bloomberg.net" <blawre@bloomberg.net>
>>>         Sent: Tue, Apr 26, 2022 at 8:21 PM
>>>         Subject: 101 STFGX par no look
>>>
>>>
>>>
>>>
>>>
>>>
>>>
>>>
>>>
>>>
>>>
>>>
>>>
>>>
>>>
>>>         Also MSGA and PAR-ID on par. 
>>>             
>>>         /s/ bd.
>>>
>>>         Sent from Yahoo Mail on Android

---


https://github.com/BSCPGROUPHOLDINGSLLC/WILSON-ELSER-DICKER-LASKOWITZ-MOV


-------- Forwarded Message --------
Subject: 	Fwd: [BSCPGROUPHOLDINGSLLC/BSCPGROUPHOLDINGSLLC] 21d041: they should also go to Prison for Tax Evasion...
Date: 	Sat, 7 May 2022 04:58:41 -0500
From: 	B D2022 <ms60710444266@yahoo.com>
To: 	Bo Dincer <bdincer66@icloud.com>



logs...
loan 50074 ---- annexed in NY Supreme MAT8TER 153974/2020


          EXHIBIT(S)  - AC0  (Motion #001)
          ACRIS Detailed Document Information (2019000021408)2019010800475001
            https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=ze6a1KA9akRV9TGfXXJT/g==
          EXHIBIT(S)  - AC1  (Motion #001)
          ACRIS Detailed Document Information (2020000155422)2020052000291003
            https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=bVk8sIt7n3kGwHqebPg0fw==
          EXHIBIT(S)  - AC2  (Motion #001)
          ACRIS Detailed Document Information (2020000155421)2020052000291002
            https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=wTG2YD2PqXuxmoKqFiESrw==
          EXHIBIT(S)  - AC3  (Motion #001)
          ACRIS Detailed Document Information (2020000155422)2020052000291003
            https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=au8qh7Dn66hrVmJ9DX_PLUS_bdg==
          EXHIBIT(S)  - AC4  (Motion #001)
          ACRIS Detailed Document Information (2020000155423)2020052000291004
            https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=/yhElCiKJ0BGv2DF/MOn4g==
          EXHIBIT(S)  - ACR  (Motion #002)
          ACRIS.NYC.GOV >> ASSIGNMENT OF LEASE AND RENTS ON FILED ON MAY 26TH - https://a836-acris.nyc.gov/
            https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=gcMSDaFzm0ynPeXZKSHgLQ==

-------------------------------------------------------------------------------------------------------------------------------------
SEQ.	PARID      	BLOCK	LOT	STREET ADDRESS		            ZIPCODE	    Market Value [MV] 	
1	1005030006	503	6	109	SULLIVAN STREET               10012	         $5,680,000       
2	1005030008	503	8	111	SULLIVAN STREET               10012	         $3,410,000 	  
3	1005030009	503	9	113	SULLIVAN STREET               10012	         $4,470,000 	     
4	1005030010	503	10	115	SULLIVAN STREET               10012	         $2,242,000 	   
5	1005030011	503	11	117	SULLIVAN STREET               10012	         $3,242,000     
6	1005030012	503	12	119	SULLIVAN STREET               10012	         $3,538,000 	   
-------------------------------------------------------------------------------------------------------------------------------------													
TOTAL SUMMARY							                                            $22,582,000 
-------------------------------------------------------------------------------------------------------------------------------------
  Log Message:
  -----------
  https://www.tdi.texas.gov/commissioner/disciplinary-orders/documents/20153854.pdf
-------------------------------------------------------------------------------------------------------------------------------------
     
### tax recceipts
https://github.com/users/BSCPGROUPHOLDINGSLLC/projects/1#column-18309490

__________________________________________________________________________________________________________________________________________________________________________________________________________
https://a836-acris.nyc.gov/DS/DocumentSearch/DocumentImageView?doc_id=2020052000291003
__________________________________________________________________________________________________________________________________________________________________________________________________________
https://a836-acris.nyc.gov/DS/DocumentSearch/DocumentImageView?doc_id=2020052000291002
__________________________________________________________________________________________________________________________________________________________________________________________________________

- warning
Wed, Jun 3, 2020, 2:20 PM        RECEIVED NYSCEF: 08/09/2020   
        "... Why don't you just tack on the 9 billion dollars NYC is in the hole while you're at it? ..."
    https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=TxAa7cNVIHKtnJU/ni/zvg==
    21 JULY 2020    NYSCEF DOC. NO. 53             RECEIVED NYSCEF:     07/21/2020
            "...REPRESENTATIVES SHOULD BE DISBARRED..."
- warning
        https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=LMUE9g_PLUS_k6vCmKgfCSJEzuQ==
- warning
        https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=TxAa7cNVIHKtnJU/ni/zvg==

https://www.sec.gov/Archives/edgar/data/0001516523/000119312522025502/d207567d4017g.htm
https://www.sec.gov/Archives/edgar/data/0000093715/999999999721005616/filename1.pdf

FROM 11-30-2021 THOUGH 03-31-2022
                                           $852,029,498.38 
...

                FOR ALL FOUR OF THE TICKERS UNDER THE FORMER UMBRELLA OF 93715
                -- MERGED INTO A LARGER BODY OF RISK UNDER THE UMBRELLA 1516523
                -- UNDER THE ADVISEMENT AND OMISSION OF ITS COUNSELORS, CONTINUE TO
                -- HEMORRHAGE ITS CAPITAL AT THE EXPENSE OF ITS INVESTORS WITHOUT
                -- ANY PUBLIC DISCLOSURE, OR ESTOPPEL BY FINRA PERMIT FOR THEM TO
                -- CONTINUE TO FUNCTION WITHOUT ANY "TRUE" SPECIALIST TO HANDLE
                -- THEIR AFFAIRS, DEMONSTRABLY AS SEEN IN THE PERFORMANCE OF THE
                -- FUND.

        ----------------------------------------------------------------------------------
            STFGX
            Date    Close/Last    Adjusted Close

            11/10/2021    121.17    121.17
            11/11/2021    120.77    120.77
            11/12/2021    121.48    121.48
                                        __________________________
                                        11/15/2021    121.34    121.34
                                        11/16/2021    121.6    121.6
                                        11/17/2021    121.52    121.52
                                        11/18/2021    121.87    121.87
                                        11/19/2021    121.69    121.69
                                        11/22/2021    121.64    121.64
                                        11/23/2021    121.79    121.79
                                        11/24/2021    121.85    121.85
                                        11/26/2021    119.44    119.44
                                        11/29/2021    120.48    120.48
                                        11/30/2021    118.5    118.5
                                        12/1/2021    117.78    117.78
                                        12/2/2021    118.95    118.95
                                        12/3/2021    118.46    118.46
                                        12/6/2021    119.95    119.95
                                        12/7/2021    121.89    121.89
                                        12/8/2021    122.51    122.51
                                        12/9/2021    121.99    121.99
                                        12/10/2021    123.25    123.25
                                        12/13/2021    122.76    122.76
                                        12/14/2021    122.16    122.16
                                        12/15/2021    124.36    124.36
                                        12/16/2021    123.55    123.55
                                        12/17/2021    121.93    121.93

        INSIDER TRADING [DECEMBER 18TH, 2021]. . . . . . . . . . . . . . . . . . . . . .[0212]
        --------------------------------------------------------------------------------------
                                                                    __________________________
                                                                    12/20/2021    120.72    120.72
                                                                    12/21/2021    106.35    106.35
                                                                    12/22/2021    107.39    107.39
                                                                    12/23/2021    108.08    108.08
                                                                    12/27/2021    109.52    109.52
                                                                    12/28/2021    109.57    109.57
                                                                    12/29/2021    109.82    109.82
                                                                    12/30/2021    109.55    109.55
                                                                    12/31/2021    109.48    109.48




  Branch: refs/heads/main
  Home:   https://github.com/BSCPGROUPHOLDINGSLLC/WILSON-ELSER-DICKER-LASKOWITZ-MOV
  Commit: 7039070eb427b45125a4b174728783b8388884d3
      https://github.com/BSCPGROUPHOLDINGSLLC/WILSON-ELSER-DICKER-LASKOWITZ-MOV/commit/7039070eb427b45125a4b174728783b8388884d3
  Author: DINCER & CO <70865813+BSCPGROUPHOLDINGSLLC@users.noreply.github.com>
  Date:   2022-05-07 (Sat, 07 May 2022)
  Changed paths:

  Log Message:

  -----------
  https://www.tdi.texas.gov/commissioner/disciplinary-orders/documents/20153854.pdf





---------------------------------------------------------------------------------------------------

---------------------------------------------------------------------------------------------------



Submission Number 16368-809-301-165 was submitted on Saturday, November 13, 2021 . . . . .  [0142]

	" Material misstatement or omission in a company's public filings 

	  or financial statements, or a failure to file ... "

	

NOTICE TO C.16 BROKERS IN [93715] on Thursday, November 25, 2021 . . . . . . . . . . . . .  [0167]



	THURSDAY, NOVEMBER 25, 2021. . . . . . . . . . . . . . . . . . . . . . . . . . .[0168]

			FROM: 	ADMIN@HUTCHMENT.COM

			SENT:	<LZUCKER@MSKYLINE.COM>, <SLASKOWITZ@INGRAMLLP.COM>, 

							<SLASKOWITZ@MSKYLINE.COM>, <ASHLEY.HUMPHRIES@WILSONELSER.COM>,

							<MSRBSUPPORT@MSRB.ORG>, <ALEX.KRESS@WILSONELSER.COM>,

							<BBREIF@BLOOMBERG.NET>, <MHARVEY13@BLOOMBERG.NET>, 

							<COLIN.BROOKS@MORGANSTANLEY.COM>, <ICEGLOBALNETWORK-INFO@ICE.COM>,

							<ICEINDICES@ICE.COM>, <ADMINISTRATOR@MSKYLINE.COM>, 

							<COMPLIANCE@T3TRADING.COM>.

							

					DOCKET 309 AND DOCKET 379 IN THE MESSAGE BODY

						"ENTIRE LOT" LEASES AND RENTS TRANSFERRED TO STATE FARM

						ALL SIX PROPERTIES WITH "NO CERTITFICATE OF OCCUPANCY"

												IN THE YEAR 2020

												AND IN THE YEAR 2022

																	   

			https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=19MVPFXy0G0QvnmRLGpYIQ==

			

			RECEIVED NYSCEF: 08/09/2020

																	   

			https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=572E8gahZUO1KFthrfiyFQ==

			RECEIVED NYSCEF: 08/10/2020

			

	Thursday, November 25, 2021. . . . . . . . . . . . . . . . . . . . . . . . . . .[0170]

			FROM: 	BO.DINCER@YAHOO.COM

			TO:		<SLASKOWITZ@INGRAMLLP.COM>, <SLASKOWITZ@INGRAMLLP.COM>,

					<SERVICE@ETRADE.COM>, <LZUCKER@MSKYLINE.COM>, <CHAIR@SEC.GOV>,

					<FIDELITY.INVESTMENTS@MAIL.FIDELITY.COM>

					

	STATE FARM. . .  . .  . .  . .  . . . . . . . . . . . . . . . . . . . . . . . . [0171]



		DOCKET 385 

		https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=K9sgXcweC7esRoSPO8MNtA==

		RECEIVED NYSCEF: 08/10/2020

		

		FROM:		B-DINCER66@OUTLOOK.COM

		SUBJECT:	RE: STATE FARM

				

		"... I INFORMED YOUR CLIENT OF THIS MATERIAL INFORMATION..."

			

		DOCKET 420

		https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=Xjn0/e1NcBADqRc_PLUS_g11P4g==

	

	JULY 21, 2020. . . . .  . .  . .  . . . . . . . . . . . . . . . . . . . . . . . [0178]

	--- THERE'S A CAMERA POINTED INTO MY APARTMENT AND AT MY LAPTOP, AND THEY MUST HAVE

		MISSED THE SPOT WHERE I CAUGHT THEM IN THE ACT EARLIER.

	

	JULY 21, 2020. . . . .  . .  . .  . . . . . . . . . . . . . . . . . . . . . . . [0181]

		--- AS STATED.

		THEY WILL DO " ANYTHING " TO AVOID PROSECUTION IN THIS RESPECT.



	

STATE FARM ASSOCIATES' FUNDS TRUST. . . . . . . . . . . . . . . . . . . . . . . . . . . . . [0183]

[FORM N-8F] 																		  2021-09-21



	" Application for Deregistration of Certain Registered Investment Companies. "

	https://www.sec.gov/Archives/edgar/data/0000093715/000119312521278180/d222043dn8f.htm

	

	THIS POSTHASTE MERGER IS THE ESSENCE OF GROSS NEGLIGENCE, WHICH IS UNDERSTOOD

	IN THE LOSSES OF ITS INVESTORS, AS THE OLD ONES HAVE NO KNOWLEDGE OF ANY MATARIALLY

	SUBSTANTIVE MATTERS, AND NOR TO THE NEW INVESTORS WHO BLINDLY INVESTED THEIR CAPITAL

	INTO THE NEW ADVISOR. CIK FILER 1519523

																

		Reason fund is applying to deregister. . . . . . . . . . . . . . . . . . . .[0184]		

				/s/ David Moore.

				Assistant Secretary

				ONE STATE FARM PLAZA

				BLOOMINGTON, IL, 61710						(309) 766-1908										

		

		Name, address and telephone number of  entity. . . . . . . . . . . . . . . .[0184]

				State Farm Investment Management Corp.

				One State Farm Plaza

				Bloomington, Illinois 61710-0001			(309) 766-1908

		

		Name and address of each principal underwriter of the fund. . . . . . . . . [0185]

				State Farm VP Management Corp.

				One State Farm Plaza

				Bloomington, Illinois 61710-0001

		

		Does the fund have any outstanding debts or any other liabilities . . . . . [0186]

		

	*** GROSS NEGLIGENCE IN MANAGING THE ASSETS AND MERGER . . . . . . . . . . . . .[0187]

	https://www.sec.gov/Archives/edgar/data/0000093715/000119312521278180/d222043dn8f.htm

	

	******  ACCOUNTING FOR THE $250.00 MIN. INVESTED IS FURTHERANCE TO THE GROSS NEGLIGENCE.

		>> ANY SOFT DOLLAR AGREEMENTS BETWEEN THE INVESTMENT ADVISER & ITS BROKERS WOULD

			ONLY ADD TO WHAT IS UNDERSTOOD AND REPORTED AS FOLLOWS.

			

				(i)  	Legal expenses: 									$240,000

				(ii) 	Accounting expenses: 			 	  		    	$  9,000

				(iiI) 	Proxy Solicitation and Tabulation					$170,000

						Prospectus Supplements and Regulatory Filings		$ 62,500

						Directors fees										$431,000

																			--------

																			$663,500

																

"If Yes, describe the nature and extent of those activities . . . . . . . . . . . . [0189]

		

	"""	  Is the fund now engaged, or intending to engage, in any business 	    """

	"""   activities other than those necessary for winding up its affairs?	    """

			

	Form N-8F application . . . . . . . . . . . . . . . . . . . . . . . [0191]

	under section 8(f) of the Investment Company Act of 1940

			



				

	VERIFICATION. . . . . . . . . . . . . . . . . . . . . . . . . . . . [0191]

	/S/ JOE R. MONK

*** DOCKET 420, 1 PAGER.

##   https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=Xjn0/e1NcBADqRc_PLUS_g11P4g==   

########################################################################################################################################################



OMISSION, FAILURE TO SUPERVISE, UNFAIR DEALING AND SECURITIES FRAUD.

--- CONTINUES WITHOUT ANY NOTICE TO THE MARKET PARTICIPANTS.



########################################################################################################################################################

*LOAN 50074, BY AND BETWEEN STATE FARM AND THE SULLIVAN PROPERTIES LP*



https://a836-acris.nyc.gov/DS/DocumentSearch/DocumentImageView?doc_id=2020052000291003



########################################################################################################################################################

.. HARBERTS IS NOT LICENSED TO CONDUCT INVESTMENT BANKING OR SECURITIES TRANSACTIONS. SIMPLY HAD THE SECRETARY NOTARIZE IT TO AVOID HIS NAME INCLUDED AS A DIRECTOR ...https://a836-acris.nyc.gov/DS/DocumentSearch/DocumentImageView?doc_id=2020052000291002

######################################################################################################################################################## 

  https://www.tdi.texas.gov/commissioner/disciplinary-orders/documents/20153854.pdf

######################################################################

A Texas subsidiary of State Farm was ordered to refund $352.5 million to residential property insurance premiums after the company's rates were found to be unreasonable in relation to the risks they covered.



######################################################STATE FARM LLOYDS

IS CURRENTLY AN OUTSIDE BUSINESS OF MR. HARBERTS AS WELL, ASSUMING A SECOND FINE WOULD BE THE GREATER OF $352,500,000.00 MILLION AS ENTERED PREVIOUSLY "to residential property insurance premiums after the company's rates were found to be unreasonable in relation to the risks they covered."



#####################################################################################

>> https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=Xjn0/e1NcBADqRc_PLUS_g11P4g==

#####################################################################################

#####################################################################################

#####################################################################################

>>>>>>  https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=H4jMXghoLMU1ozmlj4VYHg==

#####################################################################################

#####################################################################################

#####################################################################################



#####################################################################################



https://github.com/BSCPGROUPHOLDINGSLLC/ELSER-AND-DICKER/files/8601118/00420.153974_2020_Sullivan_Properties_L_P_v_Baris_Dincer_EXHIBIT_S__420.pdf



>> https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=Xjn0/e1NcBADqRc_PLUS_g11P4g==



DOCKET ANNEXED: https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=H4jMXghoLMU1ozmlj4VYHg==







------------------------------------------------------------------------



State Farm Mutual Automobile Insurance Company

credit line: $25,000,000.00



https://www.sec.gov/Archives/edgar/data/0000093715/000114554921006167/xslFormN-CEN_X01/primary_doc.xml



State Farm Mutual Automobile Insurance Company

credit line: $25,000,000.00



    Morgan Stanley & Co. LLC

    SEC file number:    008-15869

    CRD number:         8209







    2020-11-30:                    ANNUAL REPORT

    Accession number:       0001145549-21-006167

    Filed:                            2021-02-11





STFGX:    State Farm Growth Fund

$5,308,974,798.000000000000

[A] Gross commissions paid by the Fund for the reporting period: $5,657.25

[B] Aggregate brokerage commissions paid by Fund during the reporting period: $86,127.30



https://www.sec.gov/Archives/edgar/data/1516523/000114554921074536/xslFormN-CEN_X01/primary_doc.xml

THE LOSSES ARE REALIZED BY INVESTORS AS A CERTAIN " OPPORTUNITY COST " AND BENEFIT TO THE ZUCKER ORGANIZATIONS IN THE TEN YEARS PRIOR, WHO REPORTED YoY GROSS INCOME IN A LINEAR FASHION AND REPRESENT TO THE NY DFS THAT THE COMBINED VALUE OF ALL SIX PROPERTIES IS APPROXIMATELY $22.5 MILLION AND DOUBLE DIGIT RETURNS AS REFERENCED IN THE TAX RECORDS TO THE LAST TEN YEARS. THOSE LEASES AND RENTS WERE TRANSFERRED TO STATE FARM, AND IMPOSE THE UNDERLYING "GUARANTEE" OF PAYMENT IN THE EVENT OF "INSOLVENCY" OR "LATE PAYMENT" BY THE ZUCKERS -- WHO HAVE ALSO "PROMISED" TO PAY THEM BACK, SOMEWHERE ON PAGE 800 OF THE UNREGISTERED SECURITY ( THE COMBINED AND RE-STATED PROSPECTUS ) WHICH I ALSO ANNEXED IN THE MATTER OF NYSCEF 153974/2020.



UNDERSTOOD BY THE FOUR TICKERS IN QUESTION:



TICKER: STFGX

SEC FILE NUMBER: 811-01519

SERIES: S000002055

LEI: 25490064REEQMGE0GC29

CIN: C000005410

CIK: 93715



TICKER: STFBX

SEC FILE NUMBER: 811-01519

SERIES: S000002056

LEI: 254900EBILZP44C0ET43

CIN: C000005411

CIK: 93715



TICKER: SFITX

SEC FILE NUMBER: 811-01519

SERIES: S000002057

LEI: 254900QMKPLXFY2DO125

CIN: C000005412

CIK: 93715



TICKER: SFBDX

SEC FILE NUMBER: 811-01519

SERIES: S00000205

LEI: 254900XY61CSODNC1J50

CIN: C000005413

CIK: 93715



I ANNEXED THE LOAN ON THE FOURTH OF AUGUST IN 2020, AND ALSO PROVIDED NOTICE TO ALL MATERIAL PARTIES PRIOR TO THE FOURTH AND IN JUNE, CUSTODY OF MY SECURITY DEPOSIT MAY/MAY NOT HAVE BEEN COMMINGLED AND USED AS COLLATERAL AS WELL WHEN PRESENTED TO THE STATE FARM, LOCATED AT ONE STATE PLAZA, BLOOMINGTON, IL, 61710 WHERE THE CUSTODIAN HAS CHANGED. AS THEY ARE NOW SELF-ADMINISTERED AND SELF-CUSTODIED ---- WHICH IN FACT REDUCES THE COMPLIANCE/SUPERVISORY OF THE NEW FUND WITHOUT A PUBLICLY TRADED CUSTODIAN LIKE JP MORGAN TO HANDLE THEIR AFFFAIRS.



xxx THIS IS WHERE THE SHERMAN ANTI-TRUST AND FAIR DEALINGS ARE "ETHICALLY" NOT NEGOTIABLE AS THOSE RIGHTS OF BULLET-PROOF LAWSUITS MUST BE PROVIDED TO ALL REAL ESTATE HOLDERS OF PROPERTY, BOTH PUBLIC AND PRIVATE, NOTWITHSTANDING THEIR VALUATION METHOD OF ACCOUNTING... A PROVISION IN THE NEW UMBRELLA (SAVED THOSE ACCOUNTING FOR LATER, BECAUSE THEY WERE NOT COVERED BY THE 40-17G INDENTURE EXECUTED BY ITS OWN COMPLIANCE OFFICER).



FROM 11-16-2021 THROUGH 12-31-2021, WITHOUT FAIR DEALINGS AND AWARENESS FOR THE OTHER FIRMS IS UNDERSTOOD IN FEWER "PROMOTIONAL" DOLLARS AND MORE "BROKERAGE COMMISSIONS EARNED FOR SELLING AND TRANSACTIONS " WHICH CAN ALSO BE USED IN "SOFT DOLLARS" TO HELP PAY FOR THE AUDIT AND ACCOUNTING FEES. A LOSS IN PERCENTAGE VALUE IN EACH TICKER OF THE FUND, AND AFTER TAKING ON ADDITIONAL SUBSCRIPTIONS BY MAIL IS A HUGE OPPORTUNITY COST,  AND NO DISCLOSURE OF ANY MATERIAL MATTERS OR NOTICE IN A HISTORY OF FAIR-DEALINGS TO "OTHER CONSTITUENTS" - WHO BOUGHT THOSE TICKERS, JOINED AS PROMOTING BROKERS, AND WITHOUT ANY KNOWLEDGE WANTED TO KEEP THE PREMIUMS AND INTEREST.



TWO TYPES OF INCOME IS FILED: 

------------------------------------------------------------------------



STFGX:    State Farm Growth Fund

$5,308,974,798.000000000000

   [A] Gross commissions paid by the Fund for the reporting period: $5,657.25

   [B] Aggregate brokerage commissions paid by Fund during the reporting period: $86,127.30



------------------------------------------------------------------------





#GOCARDS...///



    BLOCK 803, LOT 11...



 * https://github.com/users/BSCPGROUPHOLDINGSLLC/projects/1#column-18309490



 * https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=BHKQCNuN0DHZNk5LD/32Lg==











CONTEXT:



...........................................................................................................................................................................................................................................................................................................

STFGX ............................................................................................................................................................................................................................................................................................................118.50 106.88 100.19 (6.69) -5.6456% 6,547,492,154 -642,041,003............................................................................................................................................................................................................................................................................................................ -369,643,228

...........................................................................................................................................................................................................................................................................................................

STFBX ............................................................................................................................................................................................................................................................................................................92.93 87.17 82.84 (4.33) -4.6594% ............................................................................................................................................................................................................................................................................................................2,410,114,218 .-149,384,030

........................................................................................................................................................................................................................................................................................................... -112,297,370

...........................................................................................................................................................................................................................................................................................................



SFITX...........................................................................................................................................................................................................................................................................................................10.13 9.73 9.64 (0.09) -0.8885% ............................................................................................................................................................................................................................................................................................................478,642,421   -18,899,997 ............................................................................................................................................................................................................................................................................................................-4,252,499

...........................................................................................................................................................................................................................................................................................................

SFBDX 8.91 8.40 8.16 (0.24) -2.6936% 

728,601,446 -41,704,460 

...........................................................................................................................................................................................................................................................................................................

-19,625,628

...........................................................................................................................................................................................................................................................................................................

...........................................................................................................................................................................................................................................................................................................

............................................................................................................................................................................................................................................................................................................................................................................................. 

    ##    ####    ##    ##    ##    ####    ##    ##    ##    ####    ##    ##    ##    ####    ##    ##



UNFAIR DEALINGS AND NO DISCLOSURE BY THE FIDUCIARIES OF 93715 AND 1516523. 

..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

File Date: 2020-06-08   -----------INVESTMENT COMPANY ' BLANKET 'BOND "COVERAGE"

                    ########

    ##    ####    ##    ##                 40-17G



40-17G: State Farm Associates' Funds Trust https://fintel.io/doc/sec-sfitx-state-farm-interim-fund-4017g-2020-june-08-18422-692 BOND NUMBER: 87036120B 

                    ########

    ##    ####    ##    ##



EFFECTIVE DATE BOND PERIOD: April 1, 2020 to April 1, 2021

------------------------------------------------------------------------

------------------------------------------------------------------------

------------------------------------------------------------------------

ISSUER: ICI MUTUAL INSURANCE COMPANY

APPLICATION FILED:    .........MERGER......................

------------------------------------------------------------------------

------------------------------------------------------------------------

------------------------------------------------------------------------

https://www.sec.gov/Archives/edgar/data/0000093715/999999999721005616/filename1.pdf



------------------------------------------------------------------------

------------------------------------------------------------------------

------------------------------------------------------------------------

MERGER APPLICATION : 2021-04-23 N-8F: STATE FARM ASSOCIATES' FUNDS TRUST

FILED:    .........MERGER.............................................



https://www.sec.gov/Archives/edgar/data/0000093715/000119312521278180/d222043dn8f.htm



------------------------------------------------------------------------

------------------------------------------------------------------------

------------------------------------------------------------------------

------------------------------------------------------------------------

------------------------------------------------------------------------

------------------------------------------------------------------------



NOTE: Once deregistered, a fund is still required to maintain and preserve the records described in rules 31a-l and 3la-2 for the periods specified in those rules.



------------------------------------------------------------------------

------------------------------------------------------------------------

------------------------------------------------------------------------

------------------------------------------------------------------------

------------------------------------------------------------------------

------------------------------------------------------------------------

State Farm Mutual Automobile Insurance Company

credit line: $25,000,000.00

------------------------------------------------------------------------

------------------------------------------------------------------------

------------------------------------------------------------------------

https://www.sec.gov/Archives/edgar/data/0000093715/000114554921006167/xslFormN-CEN_X01/primary_doc.xml



------------------------------------------------------------------------

     ##         ##         ##         ##    MAINTAINS THE SAME.

------------------------------------------------------------------------

------------------------------------------------------------------------



State Farm Mutual Automobile Insurance Company

     ##         ##         ##         ##    $25,000,000.00



------------------------------------------------------------------------

------------------------------------------------------------------------

------------------------------------------------------------------------

C.16 PROMOTERS.



------------------------------------------------------------------------

------------------------------------------------------------------------

    Morgan Stanley & Co. LLC

    SEC file number:    008-15869

    CRD number:         8209

     ------------------------------------------------------------------------

     ------------------------------------------------------------------------

----    individual_6507985 _ PRIYA DARSINI RAHURAM - CRD FIRM NUMBER 8209[FILED]

     ------------------------------------------------------------------------

     ------------------------------------------------------------------------

----    _CRD MEMBER MSCO_8209-BROOKS--4776256 -6109023[FILED]



     ------------------------------------------------------------------------

     ------------------------------------------------------------------------



    2020-11-30:                    ANNUAL REPORT

    Accession number:       0001145549-21-006167

    Filed:                            2021-02-11

    ------------------------------------------------------------------------

     ------------------------------------------------------------------------



      EX1/



          STFGX:    State Farm Growth Fund

            $5,308,974,798.000000000000

     [A] Gross commissions paid by the Fund for the reporting period: $5,657.25

     [B] Aggregate brokerage commissions paid by Fund during the reporting period: $86,127.30



https://www.sec.gov/Archives/edgar/data/1516523/000114554921074536/xslFormN-CEN_X01/primary_doc.xml

    ------------------------------------------------------------------------

    ------------------------------------------------------------------------



    ------------------------------------------------------------------------

    ------------------------------------------------------------------------





THE LOSSES ARE REALIZED BY INVESTORS AS A CERTAIN " OPPORTUNITY COST " AND BENEFIT TO THE ZUCKER ORGANIZATIONS IN THE TEN YEARS PRIOR, WHO REPORTED YoY GROSS INCOME IN A LINEAR FASHION FOR THE PROPERTIES TRANSFERRED TO STATE FARM AND WERE PRESENTED TO THE NY DFS THAT THE COMBINED VALUE OF ALL SIX PROPERTIES IS APPROXIMATELY ( $22.5 MILLION FOR 144 UNITS IN 2021 PRICES, IN SOHO MANHATTAN ON SULLIVAN STREET, BETWEEN PRINCE STREET AND SPRING STREET ) AND DOUBLE DIGIT RETURNS AS REFERENCED IN THE TAX RECEIPTS FOR THE LAST TEN YEARS.





    ------------------------------------------------------------------------

    ------------------------------------------------------------------------





THOSE LEASES AND RENTS WERE TRANSFERRED TO STATE FARM, AND IMPOSE THE UNDERLYING "GUARANTEE" OF PAYMENT IN THE EVENT OF "INSOLVENCY" OR "LATE PAYMENT" BY THE ZUCKER FAMILY AND ITS ORGANIZATIONS.



    ------------------------------------------------------------------------



HAVE ALSO "PROMISED" TO  REIMBURSE STATE FARM ( IN THE DOCTRINE OF A RE-STATED AMENDED AND CONSOLIDATED PROSPECTUS ) WHICH I  ANNEXED IN THE MATTER OF NYSCEF 153974/2020 AND ALSO NOTIFIED STATE FARM, AND ITS ATTORNEYS WHO HAVE NOT RESPONDED. DESPITE MY ATTEMPTS TO END THIS IN AUGUST OF 2021, THE ZUCKERS FELT IT WOULD BE BETTER TO HARASS ME IN NY SUPREME COURT TO GAIN ACCESS TO INSPECT THE UNIT ON MY TIME.

    ------------------------------------------------------------------------

EVEN ATTEMPTED TO HAVE STATE FARM RESPOND, TO NO AVAIL DECIDED TO SACRIFICE THEIR INVESTMENT ADVISER AND "MERGE" INTO A NEW SHELL AND THE GROSS NEGLIGENCE IN ACCOUNTING, AND UNFAIR DEALINGS BY ITS C.16 PROMOTERS IS NOT UNDERSTOOD BY THE "INVESTMENT COMMUNITY" DESPITE THEIR INTERESTS IN OTHER RESEARCH WHICH IS AVAILABLE FOR OTHER TICKERS, LIKE BRK-B HAS NOT MADE ANY EFFORT BEYOND COLLECTING PREMIUMS FOR THE UNDERLYING TICKERS BELOW >>>>> A FAILURE TO SUPERVISE BY ANY MEANS.



UNDERSTOOD ONLY IN THE LOSSES BY ALL FOUR TICKERS IN QUESTION:

    ------------------------------------------------------------------------



TICKER: STFGX

SEC FILE NUMBER: 811-01519

SERIES: S000002055

LEI: 25490064REEQMGE0GC29

CIN: C000005410

CIK: 93715

    ------------------------------------------------------------------------



TICKER: STFBX

SEC FILE NUMBER: 811-01519

SERIES: S000002056

LEI: 254900EBILZP44C0ET43

CIN: C000005411

CIK: 93715



TICKER: SFITX

SEC FILE NUMBER: 811-01519

SERIES: S000002057

LEI: 254900QMKPLXFY2DO125

CIN: C000005412

CIK: 93715

    ------------------------------------------------------------------------



TICKER: SFBDX

SEC FILE NUMBER: 811-01519

SERIES: S00000205

LEI: 254900XY61CSODNC1J50

CIN: C000005413

CIK: 93715

    ------------------------------------------------------------------------



I ANNEXED THE LOAN ON THE FOURTH OF AUGUST IN 2020, AND ALSO PROVIDED NOTICE TO ALL MATERIAL PARTIES PRIOR TO THE FOURTH AND IN JUNE:

    ------------------------------------------------------------------------



CUSTODY OF MY SECURITY DEPOSIT MAY/MAY NOT HAVE BEEN COMMINGLED AND USED AS COLLATERAL AS WELL WHEN PRESENTED TO THE STATE FARM, LOCATED AT ONE STATE PLAZA, BLOOMINGTON, IL, 61710. THIS IS WHERE THE SHERMAN ANTI-TRUST AND FAIR DEALINGS ARE "ETHICALLY" NOT NEGOTIABLE AS THOSE RIGHTS OF BULLET-PROOF LAWSUITS MUST BE PROVIDED TO ALL REAL ESTATE HOLDERS OF PROPERTY, BOTH PUBLIC AND PRIVATE, NOTWITHSTANDING THEIR VALUATION METHOD OF ACCOUNTING, TAX-EVASION... AND A PROVISION IN THE NEW UMBRELLA (WHO SAVED ACCOUNTING FOR LATER, BECAUSE THEY WERE NOT COVERED BY THE 40-17G INDENTURE EXECUTED BY ITS OWN COMPLIANCE OFFICERS THEN OR NOW.

    ------------------------------------------------------------------------

11-16-2021 THROUGH 12-31-2021, WITHOUT FAIR DEALINGS AND AWARENESS FOR THE OTHER FIRMS.... TCR, DATED NOVEMBER 13, 2021 , AND WITHOUT ANY FAIR NOTICE OR FAIR-DEALING TO "MARKET PARTICIPANTS" -  PROMOTED BY MORGAN STANLEY - THREE YEARS IN A ROW... IN THE OLD AND NEW INVESTMENT ADVISER CIK 1516523



   ##   

   FOR THE PREMIUMS AND INTEREST AS WELL...

   

   ##   

------------------------------------------------------------------------



   ##   TAX RECORDS ARE PUBLIC    ##   

>>>>    ONE BUILDING WITH 22 UNITS AND NO CERTIFICATE OF OCCUPANCY ( WHERE >>>>    IN NY CITY YOU CANNOT COLLECT SECURITY DEPOSITS AND RENT LEGALLY ( >>>>    AND PER THE FDIC, CANNOT CUSTODY UNLAWFULLY EARNED MONEY ) WHICH >>>>    TO MY SURPRISE WAS ALSO PRODUCING DOUBLE DIGIT RETURNS YoY FOR >>>>    THE LAST 10-YEARS. AFTER I EVALUATED THIS PROPERTY, I REVIEWED THE >>>>    OTHER PROPERTIES AND FOUND PARTIAL OR "NO CERTIFICATE OF >>>>    >>>>    OCCUPANCY AT ALL" FOR THE PROPERTIES, LEASES, AND RENTS USED AS >>>>    ASSET TO GUARANTEE AND SECURE A LOAN FROM STATE FARM IN MAY OF >>>>    2021. 

>>>>    FOR EASE OF REFERENCE HERE ARE THE QUARTERLY RECEIPTS FOR THE >>>>    LAST TEN-YEARS FOR 117 SULLIVAN STREET, NEW YORK, NY, 10012 



-------------------------------------------------------------------------------   ##   

>>>>    https://github.com/users/BSCPGROUPHOLDINGSLLC/projects/1#column-18309490 ##

>>>>    ##

>>>>    ##

>>>>    ##

   ##      ##      ##  FTC REPORT: UNLAWFUL FEES WERE NOT REFUNDED EITHER

   ##      ##      ##  " THEY CAN ALSO BE USED AS A MEANS OF GUARANTEE " 

   ##      ##      ## 

https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=BHKQCNuN0DHZNk5LD/32Lg== 

####

   ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      

   ##      ##    

   ##      ##    CONTEXT: STATE FARM ASSOCIATES FUNDS TRUST: 

   ##      ##    CIK 93715 >INTO >> FILER    ##   CIK 1516523  

##  NO DIFFERENT THAN USING ONE ATTORNEY IN A SMALLER FIRM 

   ##      ##    THEN A LARGER FIRM AS SEEN IN THE PROCEEDING OF 153974/2020

   ##      ##       https://github.com/BSCPGROUPHOLDINGSLLC/ELSER-AND-DICKER/pull/11

   ##      ##       

   ##      ##       https://github.com/BSCPGROUPHOLDINGSLLC/ELSER-AND-DICKER/pull/7

   ##      ##       *** DISTRIBUTION BY THE ATTORNEYS AT:   WILSONELSER.COM 

OF THESE ARTIFACTS HAVE NOT BEEN RESOLVED EITHER> 

   ##      ##       

   ##      ##       https://github.com/BSCPGROUPHOLDINGSLLC/ELSER-AND-DICKER/pull/5

   ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##  

ITS 100% EVASION ---- UNFAIR DEALING --- A VIOLATION OF PRIVACY ---- AND A CERTAIN LAWSUIT THAT IS ALSO BEING AVOIDED TO PROTECT ONE FAMILY HAS NOW SACRIFIED THE GREATER OF 1.35 BILLLION DOLLARS, ONE INVESTMENT ADVISER WHO MYSTERIOUSLY DECIDED TO "NO LONGER EXIST" AFTER TWENTY SEVEN YEARS UNDER CIK : 93715 AS REFERENCED BELOW.

   ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##  



SOURCE: EDGAR REPORT: 2021-11-30                                     Δ ASSET VALUE 11-30-2020 - 2022-03-31

Δ ASSET VALUE 2022-03-31 -- 04-30-2022                                  

TICKERS ##      ##      ##      ##      ##      ##      ##      ##      ##    2021-11-30  ##      ##      2022-03-31 2022-04-30 

      MoM   -4.98% IN AUM ( APPROXIMATELY ) AND 12.35% ( APPROXIMATELY ) USING THE FILED ASSETS ...

SINCE "LAST FILING" 2021-11-30  ##  BY ITS COMPLIANCE OFFICERS AND DIRECTORS AND EXECUTED BY THE DIRECTORS OF THEIR OPERATING FINANCIAL ADVISORY FIRMS.



 [STATE FARM VP 43036] STATE FARM VP MANAGEMENT CORP [    ##    DIRECTORS    ##    ]

 [STATE FARM VP 43036] Advisers Investment Trust [CIK 1516523] MONK [CRD 1357149]

##    DAVID MOORE   ##    TERRANCE "TERRY" LUDWIG   ##    PAUL SMITH

%%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%   

*** DOCKET 420, 1 PAGER.

##   https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=Xjn0/e1NcBADqRc_PLUS_g11P4g==   %%  

##    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%   

      >>>> [STATE FARM VP 43036]2992788 _ HARBERT   <<<<<<<<<

##    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%   

##    [STATE FARM VP 43036]2992788 _ HARBERT      "   STATE FARM LLOYDS  "   

##     [STATE FARM VP 43036]2992788 _ HARBERT       "  STATE FARM LIFE INSURANCE COMPANY "  

##       " STATE FARM LIFE INSURANCE COMPANY"    IS THE MANAGING ENTITY WHO IS ALSO ENCUMBERED BY LOAN 50074.

ENTITY "  STATE FARM LIFE INSURANCE COMPANY "  : : : STATE FARM REALTY MORTGAGE LLC"            %%    %%      

%%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%    %%   



##   DID NOT "RESPOND" TO THE LEGAL ACTION  AFTER HAVING CONTACTED BOTH 

<thermanson@northmarq.com> AND <jpetit@mccarter.com> 

the representatives and attorneys in the dockets filed with the NY Finance Register 



   ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##   

      >> https://a836-acris.nyc.gov/DS/DocumentSearch/DocumentImageView?doc_id=2020052000291003 <<



   ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##    

>> THIS WAS A GOOD FAITH ATTEMPT TO TERMINATE THE LOAN 50074 DURING THE 90-DAY WINDOW.

>> ENTERED AND ADMITTED ON 420 AS AN "EXHIBIT" AND WAS ALSO OBSTRUCTED BY COUNSELORS OF 'PARTY 1'



   ##   https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=Xjn0/e1NcBADqRc_PLUS_g11P4g==   %% 



   ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##    



## STFGX ## 118.50 106.88 100.19 (6.69) -5.6456% 6,547,492,154 -642,041,003       ## -369,643,228 ##



## STFBX ## 92.93 87.17 82.84 (4.33) -4.6594% 2,410,114,218 -149,384,030             ## -112,297,370 ##



## SFITX  ## 10.13 9.73 9.64 (0.09) -0.8885% 478,642,421 -18,899,997                         ## -4,252,499  ##   



## SFBDX ## 8.91 8.40 8.16 (0.24) -2.6936% 728,601,446 -41,704,460                        ## -19,625,628  ##



   ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##   

>>>>>        ##  03-30-2022  >> 04-30-2022   ##   -505,818,725  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

   ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##   

>>>>>        THE EXCESS OF FIVE HUNDRED AND FIVE MILLION US DOLLARS IN ONE MONTH <<<<

>>>>>        REPRESENTS AN ACCELERATED RATE OF LOSS WITH RESPECT TO THE PRIOR LOSSES AND >>>>>        DURING 

>>>>>        THE POSTHASTE MERGER WAS "GROSSLY NEGLIGENT"

>>>>>         AND DEMONSTRABLY AS A TOTAL OF $9000.00 ( \NINE THOUSAND DOLLARS ) 

>>>>>        WAS SET ASIDE FOR ACCOUNTING BY "  PRICE WATERHOUSE COOPERS  " 

>>>>>        [ THE PUBLICLY TRADED AUDIT FIRM ].

>>>>>        

>>>>>        

   ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##   

>>>>>        IN FURTHERANCE, THE C.16 PROMOTING BROKERS DID NOT PROVIDE ANY RESEARCH REPORT OR ANY 

>>>>>        

>>>>>        PUBLIC RELEASE TO "FAIRLY" ESTABLISH THEY HAD RECEIVED FEWER SUBSCRIPTION 

>>>>>        PREMIUMS AND MORE COMMISSIONS WITH AN ESTABLISHED "KNOWLEDGE OF THE 

>>>>>        ONGOING LEGAL MATTERS, WAS A "NON-JOINDER"

>>>>>        

>>>>>        

   ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##   

>>>>>        SUMMARY OF ASSETS AND THE CHANGE IN PERCENTAGE VALUES SINCE LAST REPORTED

>>>>>        $10,164,850,239 IN AUM AND DURING THE FILED ASSETS ON  11-30-2021 AND THE END OF 

>>>>>        THE FIRST \QUARTER IN 2022 ON 03-30-2022  LOST A TOTAL OF   $ -852,029,489  

>>>>>        WHILE 'PARTY 1' CANVASSES NEW OPPORTUNITIES FOR DEVELOPMENT

>>>>>        IN BROOKLYN ( AND WHILE THE TAXES REMAIN UNPAID

>>>>>        ARE TAXES EVADED FOR 15-YEARS

>>>>>         I STOPPED AFTER TEN YEARS BACKED UP TO ROUGHLY $250,000,000.00 ( TWO HUNDRED FIFTY MILLION IN ARREARS WITH PENALTIES UNDER  § 1.6662–2 Accuracy-related penalty.

(a) In general. Section 6662(a) imposes an accuracy-related penalty on any portion of an underpayment of tax (as defined in section 6664(a) and §1.6664–2) required to be shown on a return if such portion is attributable to one or more of the following types of misconduct: 



(1) Negligence or disregard of rules or regulations (see §1.6662–3); (2) Any substantial understatement of income tax (see §1.6662–4); or (3) Any substantial (or gross) valuation misstatement under chapter 1

(‘‘substantial valuation misstatement’’ or ‘‘gross valuation misstatement’’), provided the applicable dollar limitation set forth in section 6662(e)(2) is satisfied (see §1.6662–5).

 

   ##      https://www.govinfo.gov/content/pkg/CFR-2010-title26-vol13/pdf/CFR-2010-title26-vol13-sec1-6662-2.pdf     ## 

    >>>  

>>>>>        prior filer: STATE FARM ASSURANCES FUNDS TRUST [ CIK 93715 ]  ##      ##      ##             

    >>>        

    >>>        AUM = $0.00    

    >>>        UNDER SECTION 8(f) OF THE INVESTMENT COMPANY ACT OF 1940 

   ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##   

     #

   ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##   

FIRST..                                                                                                                                                       ##

    ##        FILED,  NOV 13, 2021,    TCR 1 [ 16368-809-301-165 ]

    ##                                                                                                                                                           ##

    ##                  https://github.com/BSCPGROUPHOLDINGSLLC/ELSER-AND-DICKER/files/8600789/_2021-11-13---TCRReport.pdf

  ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##

SECOND.

    ##        FILED,  APR 04, 2022,     TCR 2 [ 16491-117-831-823 ]                                                            ##

    ##                                                                                                                                                            ##

    ##                  https://github.com/BSCPGROUPHOLDINGSLLC/ELSER-AND-DICKER/files/8600792/_2022-04-22---TCRReport-16491-117-831-823.pdf

  ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##      ##

THIRD.

    ##       FILED, APR 28, 2022,      TCR 3 [ 16511-049-089-843 ]                                                              ##

    ##                                                                                                                                                            ##

    ##                https://github.com/BSCPGROUPHOLDINGSLLC/ELSER-AND-DICKER/files/8600857/_2022-04-28---TCRReport.16511-049-089-843.pdf



--- ---- --- -- ---- --- -- ---- --- -- ---- --- -- ---- --- --- ---- --- -- ---- --- -- ---- --- -- ---- --- -- ---- --- --- ---- --- -- ---- --- -- ---- --- -- ---- --- 



    ##       C.16 FIDUCIARY BROKERS ALSO WILL PROVIDE GUIDANCE FOR "BRK-B"    

    ##           ##           ##           ##           ##           ##           ##           ##                                   MORGAN STANLEY.

    ##       HOWEVER DID NOT REPORT ANY "MATERIAL" INFORMATION FOR ANY OF THE FOUR TICKERS.   

    ##       BETTER PROMOTE AND DISSEMINATE THE STATE FARM MUTUAL FUND ON WHAT GROUND TO EARN  

    ##       THEIR PROMOTIONAL FEES?                         

    ##       INFORMATION IN A TIMELY MANNER WHERE OTHER CONSTITUENTS 

    ##       CAN MAKE AN "INFORMED DECISION"



>>> NOT COVERED FOR OMISSIONS, OBSTRUCTION, AND THE UNFAIR DEALINGS BY ITS NEW FILER AND REPEAT C.16 PROMOTER, NAMELY MORGAN STANLEY IN THE NEW ASSURANCES FUNDS TRUST "1516523

>>> ADDRESS: ONE STATE FARM PLAZA, BLOOMINGTON, IL, 61710.



    ##       ##       ##       ##       ##       ##       ##       ##       ##       ##       ##       ##       ##   



        File Date: 2020-06-08 INVESTMENT COMPANY BLANKET BOND "COVERAGE"



    ##       ##                                                                                                                      ##

    ##             40-17G: State Farm Associates' Funds Trust                                                          

    ##                                                                                                                                 ##

    ##      https://fintel.io/doc/sec-sfitx-state-farm-interim-fund-4017g-2020-june-08-18422-692    



    ##                                                                                                                                                                   ##

    ##       BOND NUMBER: 87036120B EFFECTIVE DATE BOND PERIOD: April 1, 2020 to April 1, 2021

    ##                                                                                                                                                                   ##

    ##       ISSUER: ICI MUTUAL INSURANCE COMPANY

    ##       APPLICATION FILED: 2021-10-29



    ##                                                                                                                                                                   ## 

   

    ##       TCR FILED NOV 13, 2021 >>  DISTRIBUTED TO MORGAN STANLEY ON NOV 16, AND DEC 18 IN 2021



    ##                                                                                                                                                                   ##

    ##       NO PUBLIC DISCLOSURE OF THE LEGAL MATTERS.

    ##       HENCE --- UNFAIR DEALINGS.



    ##                                                                                                                                                                   ##

    ##                                                                                                                                                                   ##

    ##       Hearing requests should be received by the SEC by 5:30 p.m. on November 23, 2021

    ##        THE C.16 HERE  INSTEAD WATCHED STATE FARM PULL THEIR "EVASIVE MERGER" AT 

    ##                                                                                                                                                                   ##

    ##             ONE STATE FARM PLAZA, BLOOMINGTON, IL, 61710                                                             ##                                                                                                                                                            

    ##                                                                                                                                                                   ##

    ##                                                                                                                                                                   ##

    ##       https://www.sec.gov/Archives/edgar/data/0000093715/999999999721005616/filename1.pdf          ##

    ##                                                                                                                                                                   ##

    ##                                                                                                                                                                   ##

INTO:           ONE STATE FARM PLAZA, BLOOMINGTON, IL, 61710    

#########################################################################################                                                                                                                                                                 ##    

    ##       NO ASSISTANCE BY THE CONFLICTED ATTORNEYS OF SULLIVAN PROPERTIES LP                 ##

    ##                                                                                                                                                                       ##

    ##       > 101 WEST 55TH STREET, NEW YORK, NY, 10019                 <                                                        ##

    ##  https://a836-acris.nyc.gov/DS/DocumentSearch/DocumentImageView?doc_id=2020052000291002       ##                                                                                                                                                            

#########################################################################################

    ##                         ATTORNEYS FOR THE ZUCKER ORGANIZATIONS                                                         ##

    ##                                                                                                                                                                       ##

    ##                                                                                                                                                                       ##

    ##                         WILSON, DICKER, AND INGRAM                                                                                       ##

    ##                                                                                                                                                                       ##

    ##                         101 west 42nd street, New York, NY, 10017                                                                        ##

    ##                                     a shared address by TWO  law firms                                                                       ##

    ##                                                                                                                                                                   ##



__________________________

MERGER APPLICATION FILED: 2021-04-23 N-8F: STATE FARM ASSOCIATES' FUNDS TRUST

______________________________________________________________________________

https://www.sec.gov/Archives/edgar/data/0000093715/000119312521278180/d222043dn8f.htm

    ##       ##       ##       ##       ##       ##       ##       ##       ##       ##       ##       ##       ##       ##   

    ##       ##       ##       ##       ##       ##       ##       ##       ##       ##       ##       ##       ##       ##   



______________________________________________________________________________

NOTE: Once deregistered, a fund is still required to maintain and preserve the records described in rules 31a-l and 3la-2 for the periods specified in those rules. Q21, Q24: " Is the fund a party to any litigation or administrative proceeding?  "

______________________________________________________________________________

______________________________________________________________________________

______________________________________________________________________________

Fund Surviving the Merger: ####  Advisers Investment Trust   ####  [ Act File Number 811-22538 ] 

State Farm VP Management Corp. 000043036                  #### ASSETS REPORTED: 2021-11-30 ______________________________________________________________________________

______________________________________________________________________________

______________________________________________________________________________

#### https://www.sec.gov/Archives/edgar/data/0000093715/000114554922006149/xslFormN-CEN_X01/primary_doc.xml

______________________________________________________________________________

______________________________________________________________________________

______________________________________________________________________________

#### https://www.sec.gov/Archives/edgar/data/93715/999999999721005790/filename1.pdf

______________________________________________________________________________

______________________________________________________________________________

______________________________________________________________________________

#$### File Date 2020-07-28______________________________________________________________________________

______________________________________________________________________________

______________________________________________________________________________

#$###         https://fintel.io/doc/sec-stfgx-state-farm-growth-fund-ncsrs-2020-july-28-18472-569

______________________________________________________________________________

______________________________________________________________________________

______________________________________________________________________________

>> $> CODE OF ETHICS______________________________________________________________________________

______________________________________________________________________________

______________________________________________________________________________

>> $> https://fintel.io/doc/sec-stfgx-state-farm-growth-fund-ex99p-2020-march-27-18441-449

______________________________________________________________________________

______________________________________________________________________________

______________________________________________________________________________

_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________



A TOTAL OF -1,357,848,214 IN FOUR MONTHS, HOWEVER AN ACCELERATED LOSS IN MONTH PRIOR.

__________________________________________________________________________________________________________________________________________________________________________________________________________



-505,818,725 

__________________________________________________________________________________________________________________________________________________________________________________________________________

AUM: 11,016,879,728 IN THE PRIOR 11-30-2021 UNDER MANAGEMENT ON THE BASIS OF 11-30-2021 .

THE MARKET CAPITALIZATION OF THE FOUR TICKERS ABOVE REPRESENTS ADDITIONALLY SUBSCRIPTION WERE TAKEN WITHOUT ANY NOTICE TO THE NEW OR OLD INVESTORS.

__________________________________________________________________________________________________________________________________________________________________________________________________________FILED $11,016,879,728 UNDER MANAGEMENT BY THE CIK FILER 93715, WHERE ALL DIRECTORS SURVIVED THE MERGER INTO '''''''''''''CIK 1516523''''''''' AND LOAN 50074 CAN NOT BE TRANSFERRED HENCE THE SAME BROKER DEALER ''''''''''''' State Farm VP Management Corp. 000043036      AND ITS DIRECTORS AT STATE FARM, ONE STATE FARM PLAZA, BLOOMINGTON, IL, 61710 ---- DID NOT CHANGE THEIR ADDRESS EITHER.

 ''''''''''''' IN THE GROSS NEGLIGENCE, NAMELY IN THE AUDITORS IN A POSTHASTE AVOIDANCE TO CRIMINAL / CIVIL PROSECUTION WHICH WAS AIDED AND ABETTED BY THE ATTORNEYS OF SULLIVAN PROPERTIES, LP. NOTWITHSTANDING MR. REYNOSO, SEE ALSO MANHATTAN SKYLINE MANAGEMENT CORP WEBPAGE "ANNEXED" AND FILED WITH THE NYSCEF SYSTEM IN THE MATTER OF 153974/2020. FAXED 212-586-9867 DIRECTLY AND DID NOT RECEIVE A RESPONSE, HOWEVER SENT A REQUEST ABOUT AN APARTMENT IN MANHATTAN ONLINE AND RECEIVED COMMUNICATION FROM A REALTOR TO VIEW IT.



## ::::::##

              

THE TCR REPORTS HEREIN WERE DISSEMINATED TO ITS PROMOTING BROKERS IN THE PRIOR, ON NOV 16 2021, DEC 18TH 2021 AND AT ALL RELEVANT TIMES TO AVOID THIS "MERGER" INTO A REGISTERED ADVISOR WITH THREE PUBLIC AUDIT FIRMS

    ##       ##       ##       ##       ##       ##       ##       ##       ##       ##       ##       ##       ##   

__________________________________________________________________________________________________________________________________________________________________________________________________________https://github.com/BSCPGROUPHOLDINGSLLC/ELSER-AND-DICKER/files/8601202/Nov.16.2021.-.WMCKENZIE%40NYCOURTS.GOV.---.SEC.---.BOC%40BOC.NYC.GOV.pdf 



    ##       ##       ##       ##       ##       ##       ##       ##       ##       ##       ##       ##       ##   

 

__________________________________________________________________________________________________________________________________________________________________________________________________________ 

https://a836-acris.nyc.gov/DS/DocumentSearch/DocumentImageView?doc_id=2020052000291003

 

    ##       ##       ##       ##       ##       ##       ##       ##       ##       ##       ##       ##       ##   

__________________________________________________________________________________________________________________________________________________________________________________________________________ 

https://a836-acris.nyc.gov/DS/DocumentSearch/DocumentImageView?doc_id=2020052000291002



NOTE: Once deregistered, a fund is still required to maintain and preserve the records described in rules 31a-l and 3la-2 for the periods specified in those rules.State Farm Mutual Automobile Insurance Company

credit line: $25,000,000.00









-------- Forwarded Message --------
Subject: 	[BSCPGROUPHOLDINGSLLC/WILSON-ELSER-DICKER-LASKOWITZ-MOV] 703907: https://www.tdi.texas.gov/commissioner/disciplinar...
Date: 	Sat, 07 May 2022 02:39:37 -0700
From: 	DINCER & CO. <noreply@github.com>
To: 	INFO@KPMG.COM, MS60710444266@YAHOO.COM


Branch: refs/heads/main

Home: https://github.com/BSCPGROUPHOLDINGSLLC/WILSON-ELSER-DICKER-LASKOWITZ-MOV

Commit: 7039070eb427b45125a4b174728783b8388884d3

https://github.com/BSCPGROUPHOLDINGSLLC/WIL…



-------- Forwarded Message --------
Subject: 	[BSCPGROUPHOLDINGSLLC/BSCPGROUPHOLDINGSLLC] 21d041: they should also go to Prison for Tax Evasion...
Date: 	Sat, 07 May 2022 02:53:48 -0700
From: 	DINCER & CO. <noreply@github.com>
To: 	ombudsman@tdcj.texas.gov, MS60710444266@YAHOO.COM


Branch: refs/heads/main

Home: https://github.com/BSCPGROUPHOLDINGSLLC/BSCPGROUPHOLDINGSLLC

Commit: 21d0412073c471c22c35020dbab678a6449a05ee

https://github.com/BSCPGROUPHOLDINGSLLC/BSCPGROUPHOLDINGSLLC/commit/21d0412073c471c22c35020dbab678a6449a05ee

Author: DINCER & CO <70865813+BSCPGROUPHOLDINGSLLC@users.noreply.github.com>

Date: 2022-05-07 (Sat, 07 May 2022)



Changed paths:

A texas-breached



Log Message:

-----------

they should also go to Prison for Tax Evasion...



logs...

loan 50074 ---- annexed in NY Supreme MAT8TER 153974/2020





EXHIBIT(S)  - AC0  (Motion #001)

ACRIS Detailed Document Information (2019000021408)2019010800475001

https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=ze6a1KA9akRV9TGfXXJT/g==

EXHIBIT(S)  - AC1  (Motion #001)

ACRIS Detailed Document Information (2020000155422)2020052000291003

https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=bVk8sIt7n3kGwHqebPg0fw==

EXHIBIT(S)  - AC2  (Motion #001)

ACRIS Detailed Document Information (2020000155421)2020052000291002

https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=wTG2YD2PqXuxmoKqFiESrw==

EXHIBIT(S)  - AC3  (Motion #001)

ACRIS Detailed Document Information (2020000155422)2020052000291003

https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=au8qh7Dn66hrVmJ9DX_PLUS_bdg==

EXHIBIT(S)  - AC4  (Motion #001)

ACRIS Detailed Document Information (2020000155423)2020052000291004

https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=/yhElCiKJ0BGv2DF/MOn4g==

EXHIBIT(S)  - ACR  (Motion #002)

ACRIS.NYC.GOV >> ASSIGNMENT OF LEASE AND RENTS ON FILED ON MAY 26TH - https://a836-acris.nyc.gov/

https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=gcMSDaFzm0ynPeXZKSHgLQ==



-------------------------------------------------------------------------------------------------------------------------------------

SEQ. PARID BLOCK LOT STREET ADDRESS ZIPCODE Market Value [MV]

1 1005030006 503 6 109 SULLIVAN STREET 10012 $5,680,000
2 1005030008 503 8 111 SULLIVAN STREET 10012 $3,410,000
3 1005030009 503 9 113 SULLIVAN STREET 10012 $4,470,000
4 1005030010 503 10 115 SULLIVAN STREET 10012 $2,242,000
5 1005030011 503 11 117 SULLIVAN STREET 10012 $3,242,000
6 1005030012 503 12 119 SULLIVAN STREET 10012 $3,538,000
-------------------------------------------------------------------------------------------------------------------------------------

TOTAL SUMMARY $22,582,000
-------------------------------------------------------------------------------------------------------------------------------------

Log Message:

-----------

https://www.tdi.texas.gov/commissioner/disciplinary-orders/documents/20153854.pdf

-------------------------------------------------------------------------------------------------------------------------------------


### tax recceipts

https://github.com/users/BSCPGROUPHOLDINGSLLC/projects/1#column-18309490



__________________________________________________________________________________________________________________________________________________________________________________________________________

https://a836-acris.nyc.gov/DS/DocumentSearch/DocumentImageView?doc_id=2020052000291003

__________________________________________________________________________________________________________________________________________________________________________________________________________

https://a836-acris.nyc.gov/DS/DocumentSearch/DocumentImageView?doc_id=2020052000291002

__________________________________________________________________________________________________________________________________________________________________________________________________________



- warning

Wed, Jun 3, 2020, 2:20 PM RECEIVED NYSCEF: 08/09/2020
"... Why don't you just tack on the 9 billion dollars NYC is in the hole while you're at it? ..."

https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=TxAa7cNVIHKtnJU/ni/zvg==

21 JULY 2020 NYSCEF DOC. NO. 53 RECEIVED NYSCEF: 07/21/2020

"...REPRESENTATIVES SHOULD BE DISBARRED..."

- warning

https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=LMUE9g_PLUS_k6vCmKgfCSJEzuQ==

- warning

https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=TxAa7cNVIHKtnJU/ni/zvg==



https://www.sec.gov/Archives/edgar/data/0001516523/000119312522025502/d207567d4017g.htm

https://www.sec.gov/Archives/edgar/data/0000093715/999999999721005616/filename1.pdf



FROM 11-30-2021 THOUGH 03-31-2022

$852,029,498.38
..



FOR ALL FOUR OF THE TICKERS UNDER THE FORMER UMBRELLA OF 93715

-- MERGED INTO A LARGER BODY OF RISK UNDER THE UMBRELLA 1516523

-- UNDER THE ADVISEMENT AND OMISSION OF ITS COUNSELORS, CONTINUE TO

-- HEMORRHAGE ITS CAPITAL AT THE EXPENSE OF ITS INVESTORS WITHOUT

-- ANY PUBLIC DISCLOSURE, OR ESTOPPEL BY FINRA PERMIT FOR THEM TO

-- CONTINUE TO FUNCTION WITHOUT ANY "TRUE" SPECIALIST TO HANDLE

-- THEIR AFFAIRS, DEMONSTRABLY AS SEEN IN THE PERFORMANCE OF THE

-- FUND.



----------------------------------------------------------------------------------

STFGX

Date Close/Last Adjusted Close



11/10/2021 121.17 121.17

11/11/2021 120.77 120.77

11/12/2021 121.48 121.48

__________________________

11/15/2021 121.34 121.34

11/16/2021 121.6 121.6

11/17/2021 121.52 121.52

11/18/2021 121.87 121.87

11/19/2021 121.69 121.69

11/22/2021 121.64 121.64

11/23/2021 121.79 121.79

11/24/2021 121.85 121.85

11/26/2021 119.44 119.44

11/29/2021 120.48 120.48

11/30/2021 118.5 118.5

12/1/2021 117.78 117.78

12/2/2021 118.95 118.95

12/3/2021 118.46 118.46

12/6/2021 119.95 119.95

12/7/2021 121.89 121.89

12/8/2021 122.51 122.51

12/9/2021 121.99 121.99

12/10/2021 123.25 123.25

12/13/2021 122.76 122.76

12/14/2021 122.16 122.16

12/15/2021 124.36 124.36

12/16/2021 123.55 123.55

12/17/2021 121.93 121.93



INSIDER TRADING [DECEMBER 18TH, 2021]. . . . . . . . . . . . . . . . . . . . . .[0212]

--------------------------------------------------------------------------------------

__________________________

12/20/2021 120.72 120.72

12/21/2021 106.35 106.35

12/22/2021 107.39 107.39

12/23/2021 108.08 108.08

12/27/2021 109.52 109.52

12/28/2021 109.57 109.57

12/29/2021 109.82 109.82

12/30/2021 109.55 109.55

12/31/2021 109.48 109.48









Branch: refs/heads/main

Home: https://github.com/BSCPGROUPHOLDINGSLLC/WILSON-ELSER-DICKER-LASKOWITZ-MOV

Commit: 7039070eb427b45125a4b174728783b8388884d3

https://github.com/BSCPGROUPHOLDINGSLLC/WILSON-ELSER-DICKER-LASKOWITZ-MOV/commit/7039070eb427b45125a4b174728783b8388884d3

Author: DINCER & CO <70865813+BSCPGROUPHOLDINGSLLC@users.noreply.github.com>

Date: 2022-05-07 (Sat, 07 May 2022)

Changed paths:



Log Message:



-----------

https://www.tdi.texas.gov/commissioner/disciplinary-orders/documents/20153854.pdf











---------------------------------------------------------------------------------------------------



---------------------------------------------------------------------------------------------------







Submission Number 16368-809-301-165 was submitted on Saturday, November 13, 2021 . . . . . [0142]



" Material misstatement or omission in a company's public filings


or financial statements, or a failure to file ... "







NOTICE TO C.16 BROKERS IN [93715] on Thursday, November 25, 2021 . . . . . . . . . . . . . [0167]







THURSDAY, NOVEMBER 25, 2021. . . . . . . . . . . . . . . . . . . . . . . . . . .[0168]



FROM: ADMIN@HUTCHMENT.COM



SENT: <LZUCKER@MSKYLINE.COM>, <SLASKOWITZ@INGRAMLLP.COM>,


<SLASKOWITZ@MSKYLINE.COM>, <ASHLEY.HUMPHRIES@WILSONELSER.COM>,



<MSRBSUPPORT@MSRB.ORG>, <ALEX.KRESS@WILSONELSER.COM>,



<BBREIF@BLOOMBERG.NET>, <MHARVEY13@BLOOMBERG.NET>,


<COLIN.BROOKS@MORGANSTANLEY.COM>, <ICEGLOBALNETWORK-INFO@ICE.COM>,



<ICEINDICES@ICE.COM>, <ADMINISTRATOR@MSKYLINE.COM>,


<COMPLIANCE@T3TRADING.COM>.







DOCKET 309 AND DOCKET 379 IN THE MESSAGE BODY



"ENTIRE LOT" LEASES AND RENTS TRANSFERRED TO STATE FARM



ALL SIX PROPERTIES WITH "NO CERTITFICATE OF OCCUPANCY"



IN THE YEAR 2020



AND IN THE YEAR 2022






https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=19MVPFXy0G0QvnmRLGpYIQ==







RECEIVED NYSCEF: 08/09/2020






https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=572E8gahZUO1KFthrfiyFQ==



RECEIVED NYSCEF: 08/10/2020







Thursday, November 25, 2021. . . . . . . . . . . . . . . . . . . . . . . . . . .[0170]



FROM: BO.DINCER@YAHOO.COM



TO: <SLASKOWITZ@INGRAMLLP.COM>, <SLASKOWITZ@INGRAMLLP.COM>,



<SERVICE@ETRADE.COM>, <LZUCKER@MSKYLINE.COM>, <CHAIR@SEC.GOV>,



<FIDELITY.INVESTMENTS@MAIL.FIDELITY.COM>







STATE FARM. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . [0171]







DOCKET 385


https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=K9sgXcweC7esRoSPO8MNtA==



RECEIVED NYSCEF: 08/10/2020







FROM: B-DINCER66@OUTLOOK.COM



SUBJECT: RE: STATE FARM







"... I INFORMED YOUR CLIENT OF THIS MATERIAL INFORMATION..."







DOCKET 420



https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=Xjn0/e1NcBADqRc_PLUS_g11P4g==







JULY 21, 2020. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . [0178]



--- THERE'S A CAMERA POINTED INTO MY APARTMENT AND AT MY LAPTOP, AND THEY MUST HAVE



MISSED THE SPOT WHERE I CAUGHT THEM IN THE ACT EARLIER.







JULY 21, 2020. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . [0181]



--- AS STATED.



THEY WILL DO " ANYTHING " TO AVOID PROSECUTION IN THIS RESPECT.











STATE FARM ASSOCIATES' FUNDS TRUST. . . . . . . . . . . . . . . . . . . . . . . . . . . . . [0183]



[FORM N-8F] 2021-09-21







" Application for Deregistration of Certain Registered Investment Companies. "



https://www.sec.gov/Archives/edgar/data/0000093715/000119312521278180/d222043dn8f.htm







THIS POSTHASTE MERGER IS THE ESSENCE OF GROSS NEGLIGENCE, WHICH IS UNDERSTOOD



IN THE LOSSES OF ITS INVESTORS, AS THE OLD ONES HAVE NO KNOWLEDGE OF ANY MATARIALLY



SUBSTANTIVE MATTERS, AND NOR TO THE NEW INVESTORS WHO BLINDLY INVESTED THEIR CAPITAL



INTO THE NEW ADVISOR. CIK FILER 1519523







Reason fund is applying to deregister. . . . . . . . . . . . . . . . . . . .[0184]



/s/ David Moore.



Assistant Secretary



ONE STATE FARM PLAZA



BLOOMINGTON, IL, 61710 (309) 766-1908







Name, address and telephone number of entity. . . . . . . . . . . . . . . .[0184]



State Farm Investment Management Corp.



One State Farm Plaza



Bloomington, Illinois 61710-0001 (309) 766-1908







Name and address of each principal underwriter of the fund. . . . . . . . . [0185]



State Farm VP Management Corp.



One State Farm Plaza



Bloomington, Illinois 61710-0001







Does the fund have any outstanding debts or any other liabilities . . . . . [0186]







*** GROSS NEGLIGENCE IN MANAGING THE ASSETS AND MERGER . . . . . . . . . . . . .[0187]



https://www.sec.gov/Archives/edgar/data/0000093715/000119312521278180/d222043dn8f.htm







****** ACCOUNTING FOR THE $250.00 MIN. INVESTED IS FURTHERANCE TO THE GROSS NEGLIGENCE.



>> ANY SOFT DOLLAR AGREEMENTS BETWEEN THE INVESTMENT ADVISER & ITS BROKERS WOULD



ONLY ADD TO WHAT IS UNDERSTOOD AND REPORTED AS FOLLOWS.







(i) Legal expenses: $240,000



(ii) Accounting expenses: $ 9,000



(iiI) Proxy Solicitation and Tabulation $170,000



Prospectus Supplements and Regulatory Filings $ 62,500



Directors fees $431,000



--------



$663,500







"If Yes, describe the nature and extent of those activities . . . . . . . . . . . . [0189]







""" Is the fund now engaged, or intending to engage, in any business """



""" activities other than those necessary for winding up its affairs? """







Form N-8F application . . . . . . . . . . . . . . . . . . . . . . . [0191]



under section 8(f) of the Investment Company Act of 1940















VERIFICATION. . . . . . . . . . . . . . . . . . . . . . . . . . . . [0191]



/S/ JOE R. MONK



*** DOCKET 420, 1 PAGER.



## https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=Xjn0/e1NcBADqRc_PLUS_g11P4g==


########################################################################################################################################################







OMISSION, FAILURE TO SUPERVISE, UNFAIR DEALING AND SECURITIES FRAUD.



--- CONTINUES WITHOUT ANY NOTICE TO THE MARKET PARTICIPANTS.







########################################################################################################################################################



*LOAN 50074, BY AND BETWEEN STATE FARM AND THE SULLIVAN PROPERTIES LP*







https://a836-acris.nyc.gov/DS/DocumentSearch/DocumentImageView?doc_id=2020052000291003







########################################################################################################################################################



. HARBERTS IS NOT LICENSED TO CONDUCT INVESTMENT BANKING OR SECURITIES TRANSACTIONS. SIMPLY HAD THE SECRETARY NOTARIZE IT TO AVOID HIS NAME INCLUDED AS A DIRECTOR ...https://a836-acris.nyc.gov/DS/DocumentSearch/DocumentImageView?doc_id=2020052000291002



########################################################################################################################################################


https://www.tdi.texas.gov/commissioner/disciplinary-orders/documents/20153854.pdf



######################################################################



A Texas subsidiary of State Farm was ordered to refund $352.5 million to residential property insurance premiums after the company's rates were found to be unreasonable in relation to the risks they covered.







######################################################STATE FARM LLOYDS



IS CURRENTLY AN OUTSIDE BUSINESS OF MR. HARBERTS AS WELL, ASSUMING A SECOND FINE WOULD BE THE GREATER OF $352,500,000.00 MILLION AS ENTERED PREVIOUSLY "to residential property insurance premiums after the company's rates were found to be unreasonable in relation to the risks they covered."







#####################################################################################



>> https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=Xjn0/e1NcBADqRc_PLUS_g11P4g==



#####################################################################################



#####################################################################################



#####################################################################################



>>>>>> https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=H4jMXghoLMU1ozmlj4VYHg==



#####################################################################################



#####################################################################################



#####################################################################################







#####################################################################################







https://github.com/BSCPGROUPHOLDINGSLLC/ELSER-AND-DICKER/files/8601118/00420.153974_2020_Sullivan_Properties_L_P_v_Baris_Dincer_EXHIBIT_S__420.pdf







>> https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=Xjn0/e1NcBADqRc_PLUS_g11P4g==







DOCKET ANNEXED: https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=H4jMXghoLMU1ozmlj4VYHg==















------------------------------------------------------------------------







State Farm Mutual Automobile Insurance Company



credit line: $25,000,000.00







https://www.sec.gov/Archives/edgar/data/0000093715/000114554921006167/xslFormN-CEN_X01/primary_doc.xml







State Farm Mutual Automobile Insurance Company



credit line: $25,000,000.00







Morgan Stanley & Co. LLC



SEC file number: 008-15869



CRD number: 8209















2020-11-30: ANNUAL REPORT



Accession number: 0001145549-21-006167



Filed: 2021-02-11











STFGX: State Farm Growth Fund



$5,308,974,798.000000000000



[A] Gross commissions paid by the Fund for the reporting period: $5,657.25



[B] Aggregate brokerage commissions paid by Fund during the reporting period: $86,127.30







https://www.sec.gov/Archives/edgar/data/1516523/000114554921074536/xslFormN-CEN_X01/primary_doc.xml



THE LOSSES ARE REALIZED BY INVESTORS AS A CERTAIN " OPPORTUNITY COST " AND BENEFIT TO THE ZUCKER ORGANIZATIONS IN THE TEN YEARS PRIOR, WHO REPORTED YoY GROSS INCOME IN A LINEAR FASHION AND REPRESENT TO THE NY DFS THAT THE COMBINED VALUE OF ALL SIX PROPERTIES IS APPROXIMATELY $22.5 MILLION AND DOUBLE DIGIT RETURNS AS REFERENCED IN THE TAX RECORDS TO THE LAST TEN YEARS. THOSE LEASES AND RENTS WERE TRANSFERRED TO STATE FARM, AND IMPOSE THE UNDERLYING "GUARANTEE" OF PAYMENT IN THE EVENT OF "INSOLVENCY" OR "LATE PAYMENT" BY THE ZUCKERS -- WHO HAVE ALSO "PROMISED" TO PAY THEM BACK, SOMEWHERE ON PAGE 800 OF THE UNREGISTERED SECURITY ( THE COMBINED AND RE-STATED PROSPECTUS ) WHICH I ALSO ANNEXED IN THE MATTER OF NYSCEF 153974/2020.







UNDERSTOOD BY THE FOUR TICKERS IN QUESTION:







TICKER: STFGX



SEC FILE NUMBER: 811-01519



SERIES: S000002055



LEI: 25490064REEQMGE0GC29



CIN: C000005410



CIK: 93715







TICKER: STFBX



SEC FILE NUMBER: 811-01519



SERIES: S000002056



LEI: 254900EBILZP44C0ET43



CIN: C000005411



CIK: 93715







TICKER: SFITX



SEC FILE NUMBER: 811-01519



SERIES: S000002057



LEI: 254900QMKPLXFY2DO125



CIN: C000005412



CIK: 93715







TICKER: SFBDX



SEC FILE NUMBER: 811-01519



SERIES: S00000205



LEI: 254900XY61CSODNC1J50



CIN: C000005413



CIK: 93715







I ANNEXED THE LOAN ON THE FOURTH OF AUGUST IN 2020, AND ALSO PROVIDED NOTICE TO ALL MATERIAL PARTIES PRIOR TO THE FOURTH AND IN JUNE, CUSTODY OF MY SECURITY DEPOSIT MAY/MAY NOT HAVE BEEN COMMINGLED AND USED AS COLLATERAL AS WELL WHEN PRESENTED TO THE STATE FARM, LOCATED AT ONE STATE PLAZA, BLOOMINGTON, IL, 61710 WHERE THE CUSTODIAN HAS CHANGED. AS THEY ARE NOW SELF-ADMINISTERED AND SELF-CUSTODIED ---- WHICH IN FACT REDUCES THE COMPLIANCE/SUPERVISORY OF THE NEW FUND WITHOUT A PUBLICLY TRADED CUSTODIAN LIKE JP MORGAN TO HANDLE THEIR AFFFAIRS.







xxx THIS IS WHERE THE SHERMAN ANTI-TRUST AND FAIR DEALINGS ARE "ETHICALLY" NOT NEGOTIABLE AS THOSE RIGHTS OF BULLET-PROOF LAWSUITS MUST BE PROVIDED TO ALL REAL ESTATE HOLDERS OF PROPERTY, BOTH PUBLIC AND PRIVATE, NOTWITHSTANDING THEIR VALUATION METHOD OF ACCOUNTING... A PROVISION IN THE NEW UMBRELLA (SAVED THOSE ACCOUNTING FOR LATER, BECAUSE THEY WERE NOT COVERED BY THE 40-17G INDENTURE EXECUTED BY ITS OWN COMPLIANCE OFFICER).







FROM 11-16-2021 THROUGH 12-31-2021, WITHOUT FAIR DEALINGS AND AWARENESS FOR THE OTHER FIRMS IS UNDERSTOOD IN FEWER "PROMOTIONAL" DOLLARS AND MORE "BROKERAGE COMMISSIONS EARNED FOR SELLING AND TRANSACTIONS " WHICH CAN ALSO BE USED IN "SOFT DOLLARS" TO HELP PAY FOR THE AUDIT AND ACCOUNTING FEES. A LOSS IN PERCENTAGE VALUE IN EACH TICKER OF THE FUND, AND AFTER TAKING ON ADDITIONAL SUBSCRIPTIONS BY MAIL IS A HUGE OPPORTUNITY COST, AND NO DISCLOSURE OF ANY MATERIAL MATTERS OR NOTICE IN A HISTORY OF FAIR-DEALINGS TO "OTHER CONSTITUENTS" - WHO BOUGHT THOSE TICKERS, JOINED AS PROMOTING BROKERS, AND WITHOUT ANY KNOWLEDGE WANTED TO KEEP THE PREMIUMS AND INTEREST.







TWO TYPES OF INCOME IS FILED:


------------------------------------------------------------------------







STFGX: State Farm Growth Fund



$5,308,974,798.000000000000



[A] Gross commissions paid by the Fund for the reporting period: $5,657.25



[B] Aggregate brokerage commissions paid by Fund during the reporting period: $86,127.30







------------------------------------------------------------------------











#GOCARDS...///







BLOCK 803, LOT 11...







* https://github.com/users/BSCPGROUPHOLDINGSLLC/projects/1#column-18309490







* https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=BHKQCNuN0DHZNk5LD/32Lg==























CONTEXT:







......................................................................................................................................................................................................................................................................................................



STFGX ........................................................................................................................................................................................................................................................................................................118.50 106.88 100.19 (6.69) -5.6456% 6,547,492,154 -642,041,003........................................................................................................................................................................................................................................................................................................ -369,643,228



......................................................................................................................................................................................................................................................................................................



STFBX ........................................................................................................................................................................................................................................................................................................92.93 87.17 82.84 (4.33) -4.6594% ........................................................................................................................................................................................................................................................................................................2,410,114,218 .-149,384,030



...................................................................................................................................................................................................................................................................................................... -112,297,370



......................................................................................................................................................................................................................................................................................................







SFITX.......................................................................................................................................................................................................................................................................................................10.13 9.73 9.64 (0.09) -0.8885% ........................................................................................................................................................................................................................................................................................................478,642,421 -18,899,997 ........................................................................................................................................................................................................................................................................................................-4,252,499



......................................................................................................................................................................................................................................................................................................



SFBDX 8.91 8.40 8.16 (0.24) -2.6936%


728,601,446 -41,704,460


......................................................................................................................................................................................................................................................................................................



-19,625,628



......................................................................................................................................................................................................................................................................................................



......................................................................................................................................................................................................................................................................................................



.......................................................................................................................................................................................................................................................................................................................................................................................


## #### ## ## ## #### ## ## ## #### ## ## ## #### ## ##







UNFAIR DEALINGS AND NO DISCLOSURE BY THE FIDUCIARIES OF 93715 AND 1516523.


................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................



File Date: 2020-06-08 -----------INVESTMENT COMPANY ' BLANKET 'BOND "COVERAGE"



########



## #### ## ## 40-17G







40-17G: State Farm Associates' Funds Trust https://fintel.io/doc/sec-sfitx-state-farm-interim-fund-4017g-2020-june-08-18422-692 BOND NUMBER: 87036120B


########



## #### ## ##







EFFECTIVE DATE BOND PERIOD: April 1, 2020 to April 1, 2021



------------------------------------------------------------------------



------------------------------------------------------------------------



------------------------------------------------------------------------



ISSUER: ICI MUTUAL INSURANCE COMPANY



APPLICATION FILED: .........MERGER......................



------------------------------------------------------------------------



------------------------------------------------------------------------



------------------------------------------------------------------------



https://www.sec.gov/Archives/edgar/data/0000093715/999999999721005616/filename1.pdf







------------------------------------------------------------------------



------------------------------------------------------------------------



------------------------------------------------------------------------



MERGER APPLICATION : 2021-04-23 N-8F: STATE FARM ASSOCIATES' FUNDS TRUST



FILED: .........MERGER.............................................







https://www.sec.gov/Archives/edgar/data/0000093715/000119312521278180/d222043dn8f.htm







------------------------------------------------------------------------



------------------------------------------------------------------------



------------------------------------------------------------------------



------------------------------------------------------------------------



------------------------------------------------------------------------



------------------------------------------------------------------------







NOTE: Once deregistered, a fund is still required to maintain and preserve the records described in rules 31a-l and 3la-2 for the periods specified in those rules.







------------------------------------------------------------------------



------------------------------------------------------------------------



------------------------------------------------------------------------



------------------------------------------------------------------------



------------------------------------------------------------------------



------------------------------------------------------------------------



State Farm Mutual Automobile Insurance Company



credit line: $25,000,000.00



------------------------------------------------------------------------



------------------------------------------------------------------------



------------------------------------------------------------------------



https://www.sec.gov/Archives/edgar/data/0000093715/000114554921006167/xslFormN-CEN_X01/primary_doc.xml







------------------------------------------------------------------------



## ## ## ## MAINTAINS THE SAME.



------------------------------------------------------------------------



------------------------------------------------------------------------







State Farm Mutual Automobile Insurance Company



## ## ## ## $25,000,000.00







------------------------------------------------------------------------



------------------------------------------------------------------------



------------------------------------------------------------------------



C.16 PROMOTERS.







------------------------------------------------------------------------



------------------------------------------------------------------------



Morgan Stanley & Co. LLC



SEC file number: 008-15869



CRD number: 8209



------------------------------------------------------------------------



------------------------------------------------------------------------



---- individual_6507985 _ PRIYA DARSINI RAHURAM - CRD FIRM NUMBER 8209[FILED]



------------------------------------------------------------------------



------------------------------------------------------------------------



---- _CRD MEMBER MSCO_8209-BROOKS--4776256 -6109023[FILED]







------------------------------------------------------------------------



------------------------------------------------------------------------







2020-11-30: ANNUAL REPORT



Accession number: 0001145549-21-006167



Filed: 2021-02-11



------------------------------------------------------------------------



------------------------------------------------------------------------







EX1/







STFGX: State Farm Growth Fund



$5,308,974,798.000000000000



[A] Gross commissions paid by the Fund for the reporting period: $5,657.25



[B] Aggregate brokerage commissions paid by Fund during the reporting period: $86,127.30







https://www.sec.gov/Archives/edgar/data/1516523/000114554921074536/xslFormN-CEN_X01/primary_doc.xml



------------------------------------------------------------------------



------------------------------------------------------------------------







------------------------------------------------------------------------



------------------------------------------------------------------------











THE LOSSES ARE REALIZED BY INVESTORS AS A CERTAIN " OPPORTUNITY COST " AND BENEFIT TO THE ZUCKER ORGANIZATIONS IN THE TEN YEARS PRIOR, WHO REPORTED YoY GROSS INCOME IN A LINEAR FASHION FOR THE PROPERTIES TRANSFERRED TO STATE FARM AND WERE PRESENTED TO THE NY DFS THAT THE COMBINED VALUE OF ALL SIX PROPERTIES IS APPROXIMATELY ( $22.5 MILLION FOR 144 UNITS IN 2021 PRICES, IN SOHO MANHATTAN ON SULLIVAN STREET, BETWEEN PRINCE STREET AND SPRING STREET ) AND DOUBLE DIGIT RETURNS AS REFERENCED IN THE TAX RECEIPTS FOR THE LAST TEN YEARS.











------------------------------------------------------------------------



------------------------------------------------------------------------











THOSE LEASES AND RENTS WERE TRANSFERRED TO STATE FARM, AND IMPOSE THE UNDERLYING "GUARANTEE" OF PAYMENT IN THE EVENT OF "INSOLVENCY" OR "LATE PAYMENT" BY THE ZUCKER FAMILY AND ITS ORGANIZATIONS.







------------------------------------------------------------------------







HAVE ALSO "PROMISED" TO REIMBURSE STATE FARM ( IN THE DOCTRINE OF A RE-STATED AMENDED AND CONSOLIDATED PROSPECTUS ) WHICH I ANNEXED IN THE MATTER OF NYSCEF 153974/2020 AND ALSO NOTIFIED STATE FARM, AND ITS ATTORNEYS WHO HAVE NOT RESPONDED. DESPITE MY ATTEMPTS TO END THIS IN AUGUST OF 2021, THE ZUCKERS FELT IT WOULD BE BETTER TO HARASS ME IN NY SUPREME COURT TO GAIN ACCESS TO INSPECT THE UNIT ON MY TIME.



------------------------------------------------------------------------



EVEN ATTEMPTED TO HAVE STATE FARM RESPOND, TO NO AVAIL DECIDED TO SACRIFICE THEIR INVESTMENT ADVISER AND "MERGE" INTO A NEW SHELL AND THE GROSS NEGLIGENCE IN ACCOUNTING, AND UNFAIR DEALINGS BY ITS C.16 PROMOTERS IS NOT UNDERSTOOD BY THE "INVESTMENT COMMUNITY" DESPITE THEIR INTERESTS IN OTHER RESEARCH WHICH IS AVAILABLE FOR OTHER TICKERS, LIKE BRK-B HAS NOT MADE ANY EFFORT BEYOND COLLECTING PREMIUMS FOR THE UNDERLYING TICKERS BELOW >>>>> A FAILURE TO SUPERVISE BY ANY MEANS.







UNDERSTOOD ONLY IN THE LOSSES BY ALL FOUR TICKERS IN QUESTION:



------------------------------------------------------------------------







TICKER: STFGX



SEC FILE NUMBER: 811-01519



SERIES: S000002055



LEI: 25490064REEQMGE0GC29



CIN: C000005410



CIK: 93715



------------------------------------------------------------------------







TICKER: STFBX



SEC FILE NUMBER: 811-01519



SERIES: S000002056



LEI: 254900EBILZP44C0ET43



CIN: C000005411



CIK: 93715







TICKER: SFITX



SEC FILE NUMBER: 811-01519



SERIES: S000002057



LEI: 254900QMKPLXFY2DO125



CIN: C000005412



CIK: 93715



------------------------------------------------------------------------







TICKER: SFBDX



SEC FILE NUMBER: 811-01519



SERIES: S00000205



LEI: 254900XY61CSODNC1J50



CIN: C000005413



CIK: 93715



------------------------------------------------------------------------







I ANNEXED THE LOAN ON THE FOURTH OF AUGUST IN 2020, AND ALSO PROVIDED NOTICE TO ALL MATERIAL PARTIES PRIOR TO THE FOURTH AND IN JUNE:



------------------------------------------------------------------------







CUSTODY OF MY SECURITY DEPOSIT MAY/MAY NOT HAVE BEEN COMMINGLED AND USED AS COLLATERAL AS WELL WHEN PRESENTED TO THE STATE FARM, LOCATED AT ONE STATE PLAZA, BLOOMINGTON, IL, 61710. THIS IS WHERE THE SHERMAN ANTI-TRUST AND FAIR DEALINGS ARE "ETHICALLY" NOT NEGOTIABLE AS THOSE RIGHTS OF BULLET-PROOF LAWSUITS MUST BE PROVIDED TO ALL REAL ESTATE HOLDERS OF PROPERTY, BOTH PUBLIC AND PRIVATE, NOTWITHSTANDING THEIR VALUATION METHOD OF ACCOUNTING, TAX-EVASION... AND A PROVISION IN THE NEW UMBRELLA (WHO SAVED ACCOUNTING FOR LATER, BECAUSE THEY WERE NOT COVERED BY THE 40-17G INDENTURE EXECUTED BY ITS OWN COMPLIANCE OFFICERS THEN OR NOW.



------------------------------------------------------------------------



11-16-2021 THROUGH 12-31-2021, WITHOUT FAIR DEALINGS AND AWARENESS FOR THE OTHER FIRMS.... TCR, DATED NOVEMBER 13, 2021 , AND WITHOUT ANY FAIR NOTICE OR FAIR-DEALING TO "MARKET PARTICIPANTS" - PROMOTED BY MORGAN STANLEY - THREE YEARS IN A ROW... IN THE OLD AND NEW INVESTMENT ADVISER CIK 1516523







##


FOR THE PREMIUMS AND INTEREST AS WELL...






##


------------------------------------------------------------------------







## TAX RECORDS ARE PUBLIC ##


>>>> ONE BUILDING WITH 22 UNITS AND NO CERTIFICATE OF OCCUPANCY ( WHERE >>>> IN NY CITY YOU CANNOT COLLECT SECURITY DEPOSITS AND RENT LEGALLY ( >>>> AND PER THE FDIC, CANNOT CUSTODY UNLAWFULLY EARNED MONEY ) WHICH >>>> TO MY SURPRISE WAS ALSO PRODUCING DOUBLE DIGIT RETURNS YoY FOR >>>> THE LAST 10-YEARS. AFTER I EVALUATED THIS PROPERTY, I REVIEWED THE >>>> OTHER PROPERTIES AND FOUND PARTIAL OR "NO CERTIFICATE OF >>>> >>>> OCCUPANCY AT ALL" FOR THE PROPERTIES, LEASES, AND RENTS USED AS >>>> ASSET TO GUARANTEE AND SECURE A LOAN FROM STATE FARM IN MAY OF >>>> 2021. 



>>>> FOR EASE OF REFERENCE HERE ARE THE QUARTERLY RECEIPTS FOR THE >>>> LAST TEN-YEARS FOR 117 SULLIVAN STREET, NEW YORK, NY, 10012 







------------------------------------------------------------------------------- ##


>>>> https://github.com/users/BSCPGROUPHOLDINGSLLC/projects/1#column-18309490 ##



>>>> ##



>>>> ##



>>>> ##



## ## ## FTC REPORT: UNLAWFUL FEES WERE NOT REFUNDED EITHER



## ## ## " THEY CAN ALSO BE USED AS A MEANS OF GUARANTEE "


## ## ##


https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=BHKQCNuN0DHZNk5LD/32Lg==


####



## ## ## ## ## ## ## ## ## ## ## ## ## ## ##


## ##


## ## CONTEXT: STATE FARM ASSOCIATES FUNDS TRUST:


## ## CIK 93715 >INTO >> FILER ## CIK 1516523


## NO DIFFERENT THAN USING ONE ATTORNEY IN A SMALLER FIRM


## ## THEN A LARGER FIRM AS SEEN IN THE PROCEEDING OF 153974/2020



## ## https://github.com/BSCPGROUPHOLDINGSLLC/ELSER-AND-DICKER/pull/11



## ##


## ## https://github.com/BSCPGROUPHOLDINGSLLC/ELSER-AND-DICKER/pull/7



## ## *** DISTRIBUTION BY THE ATTORNEYS AT: WILSONELSER.COM


OF THESE ARTIFACTS HAVE NOT BEEN RESOLVED EITHER>


## ##


## ## https://github.com/BSCPGROUPHOLDINGSLLC/ELSER-AND-DICKER/pull/5



## ## ## ## ## ## ## ## ## ## ## ## ## ## ##


ITS 100% EVASION ---- UNFAIR DEALING --- A VIOLATION OF PRIVACY ---- AND A CERTAIN LAWSUIT THAT IS ALSO BEING AVOIDED TO PROTECT ONE FAMILY HAS NOW SACRIFIED THE GREATER OF 1.35 BILLLION DOLLARS, ONE INVESTMENT ADVISER WHO MYSTERIOUSLY DECIDED TO "NO LONGER EXIST" AFTER TWENTY SEVEN YEARS UNDER CIK : 93715 AS REFERENCED BELOW.



## ## ## ## ## ## ## ## ## ## ## ## ## ## ##






SOURCE: EDGAR REPORT: 2021-11-30 Δ ASSET VALUE 11-30-2020 - 2022-03-31



Δ ASSET VALUE 2022-03-31 -- 04-30-2022


TICKERS ## ## ## ## ## ## ## ## ## 2021-11-30 ## ## 2022-03-31 2022-04-30


MoM -4.98% IN AUM ( APPROXIMATELY ) AND 12.35% ( APPROXIMATELY ) USING THE FILED ASSETS ...



SINCE "LAST FILING" 2021-11-30 ## BY ITS COMPLIANCE OFFICERS AND DIRECTORS AND EXECUTED BY THE DIRECTORS OF THEIR OPERATING FINANCIAL ADVISORY FIRMS.







[STATE FARM VP 43036] STATE FARM VP MANAGEMENT CORP [ ## DIRECTORS ## ]



[STATE FARM VP 43036] Advisers Investment Trust [CIK 1516523] MONK [CRD 1357149]



## DAVID MOORE ## TERRANCE "TERRY" LUDWIG ## PAUL SMITH



%% %% %% %% %% %% %% %% %% %% %% %% %% %% %% %% %% %% %%


*** DOCKET 420, 1 PAGER.



## https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=Xjn0/e1NcBADqRc_PLUS_g11P4g== %%


## %% %% %% %% %% %% %% %% %% %% %% %% %% %% %% %% %% %%


>>>> [STATE FARM VP 43036]2992788 _ HARBERT <<<<<<<<<



## %% %% %% %% %% %% %% %% %% %% %% %% %% %% %% %% %% %%


## [STATE FARM VP 43036]2992788 _ HARBERT " STATE FARM LLOYDS "


## [STATE FARM VP 43036]2992788 _ HARBERT " STATE FARM LIFE INSURANCE COMPANY "


## " STATE FARM LIFE INSURANCE COMPANY" IS THE MANAGING ENTITY WHO IS ALSO ENCUMBERED BY LOAN 50074.



ENTITY " STATE FARM LIFE INSURANCE COMPANY " : : : STATE FARM REALTY MORTGAGE LLC" %% %%


%% %% %% %% %% %% %% %% %% %% %% %% %% %% %% %% %% %% %%






## DID NOT "RESPOND" TO THE LEGAL ACTION AFTER HAVING CONTACTED BOTH


<thermanson@northmarq.com> AND <jpetit@mccarter.com>


the representatives and attorneys in the dockets filed with the NY Finance Register






## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##


>> https://a836-acris.nyc.gov/DS/DocumentSearch/DocumentImageView?doc_id=2020052000291003 <<







## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##


>> THIS WAS A GOOD FAITH ATTEMPT TO TERMINATE THE LOAN 50074 DURING THE 90-DAY WINDOW.



>> ENTERED AND ADMITTED ON 420 AS AN "EXHIBIT" AND WAS ALSO OBSTRUCTED BY COUNSELORS OF 'PARTY 1'







## https://iapps.courts.state.ny.us/nyscef/ViewDocument?docIndex=Xjn0/e1NcBADqRc_PLUS_g11P4g== %%






## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##






## STFGX ## 118.50 106.88 100.19 (6.69) -5.6456% 6,547,492,154 -642,041,003 ## -369,643,228 ##







## STFBX ## 92.93 87.17 82.84 (4.33) -4.6594% 2,410,114,218 -149,384,030 ## -112,297,370 ##







## SFITX ## 10.13 9.73 9.64 (0.09) -0.8885% 478,642,421 -18,899,997 ## -4,252,499 ##






## SFBDX ## 8.91 8.40 8.16 (0.24) -2.6936% 728,601,446 -41,704,460 ## -19,625,628 ##







## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##


>>>>> ## 03-30-2022 >> 04-30-2022 ## -505,818,725 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<



## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##


>>>>> THE EXCESS OF FIVE HUNDRED AND FIVE MILLION US DOLLARS IN ONE MONTH <<<<



>>>>> REPRESENTS AN ACCELERATED RATE OF LOSS WITH RESPECT TO THE PRIOR LOSSES AND >>>>> DURING 



>>>>> THE POSTHASTE MERGER WAS "GROSSLY NEGLIGENT"



>>>>> AND DEMONSTRABLY AS A TOTAL OF $9000.00 ( \NINE THOUSAND DOLLARS ) 



>>>>> WAS SET ASIDE FOR ACCOUNTING BY " PRICE WATERHOUSE COOPERS " 



>>>>> [ THE PUBLICLY TRADED AUDIT FIRM ].









## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##


>>>>> IN FURTHERANCE, THE C.16 PROMOTING BROKERS DID NOT PROVIDE ANY RESEARCH REPORT OR ANY 






>>>>> PUBLIC RELEASE TO "FAIRLY" ESTABLISH THEY HAD RECEIVED FEWER SUBSCRIPTION 



>>>>> PREMIUMS AND MORE COMMISSIONS WITH AN ESTABLISHED "KNOWLEDGE OF THE 



>>>>> ONGOING LEGAL MATTERS, WAS A "NON-JOINDER"









## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##


>>>>> SUMMARY OF ASSETS AND THE CHANGE IN PERCENTAGE VALUES SINCE LAST REPORTED



>>>>> $10,164,850,239 IN AUM AND DURING THE FILED ASSETS ON 11-30-2021 AND THE END OF 



>>>>> THE FIRST \QUARTER IN 2022 ON 03-30-2022 LOST A TOTAL OF $ -852,029,489 



>>>>> WHILE 'PARTY 1' CANVASSES NEW OPPORTUNITIES FOR DEVELOPMENT



>>>>> IN BROOKLYN ( AND WHILE THE TAXES REMAIN UNPAID



>>>>> ARE TAXES EVADED FOR 15-YEARS



>>>>> I STOPPED AFTER TEN YEARS BACKED UP TO ROUGHLY $250,000,000.00 ( TWO HUNDRED FIFTY MILLION IN ARREARS WITH PENALTIES UNDER § 1.6662–2 Accuracy-related penalty.



(a) In general. Section 6662(a) imposes an accuracy-related penalty on any portion of an underpayment of tax (as defined in section 6664(a) and §1.6664–2) required to be shown on a return if such portion is attributable to one or more of the following types of misconduct:






(1) Negligence or disregard of rules or regulations (see §1.6662–3); (2) Any substantial understatement of income tax (see §1.6662–4); or (3) Any substantial (or gross) valuation misstatement under chapter 1



(‘‘substantial valuation misstatement’’ or ‘‘gross valuation misstatement’’), provided the applicable dollar limitation set forth in section 6662(e)(2) is satisfied (see §1.6662–5).






## https://www.govinfo.gov/content/pkg/CFR-2010-title26-vol13/pdf/CFR-2010-title26-vol13-sec1-6662-2.pdf ##


>>>


>>>>> prior filer: STATE FARM ASSURANCES FUNDS TRUST [ CIK 93715 ] ## ## ## 



>>>


>>> AUM = $0.00


>>> UNDER SECTION 8(f) OF THE INVESTMENT COMPANY ACT OF 1940


## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##


#



## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##


FIRST.. ##



## FILED, NOV 13, 2021, TCR 1 [ 16368-809-301-165 ]



## ##



## https://github.com/BSCPGROUPHOLDINGSLLC/ELSER-AND-DICKER/files/8600789/_2021-11-13---TCRReport.pdf



## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##



SECOND.



## FILED, APR 04, 2022, TCR 2 [ 16491-117-831-823 ] ##



## ##



## https://github.com/BSCPGROUPHOLDINGSLLC/ELSER-AND-DICKER/files/8600792/_2022-04-22---TCRReport-16491-117-831-823.pdf



## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##



THIRD.



## FILED, APR 28, 2022, TCR 3 [ 16511-049-089-843 ] ##



## ##



## https://github.com/BSCPGROUPHOLDINGSLLC/ELSER-AND-DICKER/files/8600857/_2022-04-28---TCRReport.16511-049-089-843.pdf







--- ---- --- -- ---- --- -- ---- --- -- ---- --- -- ---- --- --- ---- --- -- ---- --- -- ---- --- -- ---- --- -- ---- --- --- ---- --- -- ---- --- -- ---- --- -- ---- ---






## C.16 FIDUCIARY BROKERS ALSO WILL PROVIDE GUIDANCE FOR "BRK-B"


## ## ## ## ## ## ## ## MORGAN STANLEY.



## HOWEVER DID NOT REPORT ANY "MATERIAL" INFORMATION FOR ANY OF THE FOUR TICKERS.


## BETTER PROMOTE AND DISSEMINATE THE STATE FARM MUTUAL FUND ON WHAT GROUND TO EARN


## THEIR PROMOTIONAL FEES?


## INFORMATION IN A TIMELY MANNER WHERE OTHER CONSTITUENTS


## CAN MAKE AN "INFORMED DECISION"







>>> NOT COVERED FOR OMISSIONS, OBSTRUCTION, AND THE UNFAIR DEALINGS BY ITS NEW FILER AND REPEAT C.16 PROMOTER, NAMELY MORGAN STANLEY IN THE NEW ASSURANCES FUNDS TRUST "1516523



>>> ADDRESS: ONE STATE FARM PLAZA, BLOOMINGTON, IL, 61710.







## ## ## ## ## ## ## ## ## ## ## ## ##






File Date: 2020-06-08 INVESTMENT COMPANY BLANKET BOND "COVERAGE"







## ## ##



## 40-17G: State Farm Associates' Funds Trust


## ##



## https://fintel.io/doc/sec-sfitx-state-farm-interim-fund-4017g-2020-june-08-18422-692






## ##



## BOND NUMBER: 87036120B EFFECTIVE DATE BOND PERIOD: April 1, 2020 to April 1, 2021



## ##



## ISSUER: ICI MUTUAL INSURANCE COMPANY



## APPLICATION FILED: 2021-10-29







## ##





## TCR FILED NOV 13, 2021 >> DISTRIBUTED TO MORGAN STANLEY ON NOV 16, AND DEC 18 IN 2021







## ##



## NO PUBLIC DISCLOSURE OF THE LEGAL MATTERS.



## HENCE --- UNFAIR DEALINGS.







## ##



## ##



## Hearing requests should be received by the SEC by 5:30 p.m. on November 23, 2021



## THE C.16 HERE INSTEAD WATCHED STATE FARM PULL THEIR "EVASIVE MERGER" AT


## ##



## ONE STATE FARM PLAZA, BLOOMINGTON, IL, 61710 ##


## ##



## ##



## https://www.sec.gov/Archives/edgar/data/0000093715/999999999721005616/filename1.pdf ##



## ##



## ##



INTO: ONE STATE FARM PLAZA, BLOOMINGTON, IL, 61710


######################################################################################### ##


## NO ASSISTANCE BY THE CONFLICTED ATTORNEYS OF SULLIVAN PROPERTIES LP ##



## ##



## > 101 WEST 55TH STREET, NEW YORK, NY, 10019 < ##



## https://a836-acris.nyc.gov/DS/DocumentSearch/DocumentImageView?doc_id=2020052000291002 ##


#########################################################################################



## ATTORNEYS FOR THE ZUCKER ORGANIZATIONS ##



## ##



## ##



## WILSON, DICKER, AND INGRAM ##



## ##



## 101 west 42nd street, New York, NY, 10017 ##



## a shared address by TWO law firms ##



## ##







__________________________



MERGER APPLICATION FILED: 2021-04-23 N-8F: STATE FARM ASSOCIATES' FUNDS TRUST



______________________________________________________________________________



https://www.sec.gov/Archives/edgar/data/0000093715/000119312521278180/d222043dn8f.htm



## ## ## ## ## ## ## ## ## ## ## ## ## ##


## ## ## ## ## ## ## ## ## ## ## ## ## ##






______________________________________________________________________________



NOTE: Once deregistered, a fund is still required to maintain and preserve the records described in rules 31a-l and 3la-2 for the periods specified in those rules. Q21, Q24: " Is the fund a party to any litigation or administrative proceeding? "



______________________________________________________________________________



______________________________________________________________________________



______________________________________________________________________________



Fund Surviving the Merger: #### Advisers Investment Trust #### [ Act File Number 811-22538 ]


State Farm VP Management Corp. 000043036 #### ASSETS REPORTED: 2021-11-30 ______________________________________________________________________________



______________________________________________________________________________



______________________________________________________________________________



#### https://www.sec.gov/Archives/edgar/data/0000093715/000114554922006149/xslFormN-CEN_X01/primary_doc.xml



______________________________________________________________________________



______________________________________________________________________________



______________________________________________________________________________



#### https://www.sec.gov/Archives/edgar/data/93715/999999999721005790/filename1.pdf



______________________________________________________________________________



______________________________________________________________________________



______________________________________________________________________________



#$### File Date 2020-07-28______________________________________________________________________________



______________________________________________________________________________



______________________________________________________________________________



#$### https://fintel.io/doc/sec-stfgx-state-farm-growth-fund-ncsrs-2020-july-28-18472-569



______________________________________________________________________________



______________________________________________________________________________



______________________________________________________________________________



>> $> CODE OF ETHICS______________________________________________________________________________



______________________________________________________________________________



______________________________________________________________________________



>> $> https://fintel.io/doc/sec-stfgx-state-farm-growth-fund-ex99p-2020-march-27-18441-449



______________________________________________________________________________



______________________________________________________________________________



______________________________________________________________________________



_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________







A TOTAL OF -1,357,848,214 IN FOUR MONTHS, HOWEVER AN ACCELERATED LOSS IN MONTH PRIOR.



__________________________________________________________________________________________________________________________________________________________________________________________________________







-505,818,725


__________________________________________________________________________________________________________________________________________________________________________________________________________



AUM: 11,016,879,728 IN THE PRIOR 11-30-2021 UNDER MANAGEMENT ON THE BASIS OF 11-30-2021 .



THE MARKET CAPITALIZATION OF THE FOUR TICKERS ABOVE REPRESENTS ADDITIONALLY SUBSCRIPTION WERE TAKEN WITHOUT ANY NOTICE TO THE NEW OR OLD INVESTORS.



__________________________________________________________________________________________________________________________________________________________________________________________________________FILED $11,016,879,728 UNDER MANAGEMENT BY THE CIK FILER 93715, WHERE ALL DIRECTORS SURVIVED THE MERGER INTO '''''''''''''CIK 1516523''''''''' AND LOAN 50074 CAN NOT BE TRANSFERRED HENCE THE SAME BROKER DEALER ''''''''''''' State Farm VP Management Corp. 000043036 AND ITS DIRECTORS AT STATE FARM, ONE STATE FARM PLAZA, BLOOMINGTON, IL, 61710 ---- DID NOT CHANGE THEIR ADDRESS EITHER.



''''''''''''' IN THE GROSS NEGLIGENCE, NAMELY IN THE AUDITORS IN A POSTHASTE AVOIDANCE TO CRIMINAL / CIVIL PROSECUTION WHICH WAS AIDED AND ABETTED BY THE ATTORNEYS OF SULLIVAN PROPERTIES, LP. NOTWITHSTANDING MR. REYNOSO, SEE ALSO MANHATTAN SKYLINE MANAGEMENT CORP WEBPAGE "ANNEXED" AND FILED WITH THE NYSCEF SYSTEM IN THE MATTER OF 153974/2020. FAXED 212-586-9867 DIRECTLY AND DID NOT RECEIVE A RESPONSE, HOWEVER SENT A REQUEST ABOUT AN APARTMENT IN MANHATTAN ONLINE AND RECEIVED COMMUNICATION FROM A REALTOR TO VIEW IT.







## ::::::##






THE TCR REPORTS HEREIN WERE DISSEMINATED TO ITS PROMOTING BROKERS IN THE PRIOR, ON NOV 16 2021, DEC 18TH 2021 AND AT ALL RELEVANT TIMES TO AVOID THIS "MERGER" INTO A REGISTERED ADVISOR WITH THREE PUBLIC AUDIT FIRMS



## ## ## ## ## ## ## ## ## ## ## ## ##


__________________________________________________________________________________________________________________________________________________________________________________________________________https://github.com/BSCPGROUPHOLDINGSLLC/ELSER-AND-DICKER/files/8601202/Nov.16.2021.-.WMCKENZIE%40NYCOURTS.GOV.---.SEC.---.BOC%40BOC.NYC.GOV.pdf






## ## ## ## ## ## ## ## ## ## ## ## ##





__________________________________________________________________________________________________________________________________________________________________________________________________________


https://a836-acris.nyc.gov/DS/DocumentSearch/DocumentImageView?doc_id=2020052000291003






## ## ## ## ## ## ## ## ## ## ## ## ##


__________________________________________________________________________________________________________________________________________________________________________________________________________


https://a836-acris.nyc.gov/DS/DocumentSearch/DocumentImageView?doc_id=2020052000291002







NOTE: Once deregistered, a fund is still required to maintain and preserve the records described in rules 31a-l and 3la-2 for the periods specified in those rules.State Farm Mutual Automobile Insurance Company



credit line: $25,000,000.00



















-------- Forwarded Message --------

Subject: [BSCPGROUPHOLDINGSLLC/WILSON-ELSER-DICKER-LASKOWITZ-MOV] 703907: https://www.tdi.texas.gov/commissioner/disciplinar...

Date: Sat, 07 May 2022 02:39:37 -0700

From: DINCER & CO. <noreply@github.com>

To: INFO@KPMG.COM, MS60710444266@YAHOO.COM





Branch: refs/heads/main



Home: https://github.com/BSCPGROUPHOLDINGSLLC/WILSON-ELSER-DICKER-LASKOWITZ-MOV



Commit: 7039070eb427b45125a4b174728783b8388884d3



https://github.com/BSCPGROUPHOLDINGSLLC/WIL…






![image](https://user-images.githubusercontent.com/70865813/167268583-fac93169-9948-478f-9ba1-9105772d201c.png)


---
ABOUT YOUR PROPERTY TAXES ON 117 SULLIVAN STREET
- TRANSFERRED TO: STATE FARM


https://a836-pts-access.nyc.gov/care/Datalets/PrintDatalet.aspx?pin=1005030011&gsp=ASMT_FIN_2021&taxyear=2022&jur=65&ownseq=0&card=1&roll=RP_NY&State=1&item=1&items=-1&all=undefined&ranks=Datalet


																							117 SULLIVAN STREET
																							NEW YORK, NY, 10012
<br>

	
<table style="width:90%; border: 0px; background-color: #96D4D4; height: 5px; margin-left: 30px;">
  <tr>
    <td style="text-align: left;"><strong>2010-01-15</strong></td>
    <td style="text-align: right;"><strong>0005</strong></td>
	</tr>
</table>
<br>

>>>[2010-2011:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q1: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20100611&stmtType=SOA)

>>>[2010-2011:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q2: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20100827&stmtType=SOA)

>>>[2010-2011:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q3: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20101119&stmtType=SOA)

>>>[2010-2011:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q4: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20110218&stmtType=SOA)

	
<table style="width:90%; border: 0px; background-color: #96D4D4; height: 5px; margin-left: 30px;">
  <tr>
    <td style="text-align: left;"><strong>2011-01-15</strong></td>
    <td style="text-align: right;"><strong>0005</strong></td>
	</tr>
</table>
<br>

>>>[2011-2012:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q1: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20110610&stmtType=SOA)

>>>[2011-2012:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q2: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20110826&stmtType=SOA)

>>>[2011-2012:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q3: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20111118&stmtType=SOA)

>>>[2011-2012:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q4: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20120224&stmtType=SOA)

<table style="width:90%; border: 0px; background-color: #96D4D4; height: 5px; margin-left: 30px;">
    <tr style=" padding-top: 0px;">
    <td style="text-align: left;"><strong>2012-01-15</strong></td>
    <td style="text-align: right;"><strong>0007</strong></td>
</table>
<br>

>>>[2012-2013:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q4: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20130222&stmtType=SOA)

>>>[2012-2013:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q3: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20121130&stmtType=SOA)

>>>[2012-2013:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q2: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20120817&stmtType=SOA)

>>>[2012-2013:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q1: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20120608&stmtType=SOA)

<table style="width:90%; border: 0px; background-color: #96D4D4; height: 5px; margin-left: 30px;">
    <tr style=" padding-top: 0px;">
    <td style="text-align: left;"><strong>2013-01-15</strong></td>
    <td style="text-align: right;"><strong>0009</strong></td>
  </tr>
</table>
<br>

>>>[2013-2014:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q1: NYC ](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20130607&stmtType=SOA)

>>>[2013-2014:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q2: NYC ](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20130823&stmtType=SOA)

>>>[2013-2014:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q3: NYC ](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20131122&stmtType=SOA)

>>>[2013-2014:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q4: NYC ](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20140221&stmtType=SOA)
 
 
<table style="width:90%; border: 0px; background-color: #96D4D4; height: 5px; margin-left: 30px;">
    <tr style=" padding-top: 0px;">
    <td style="text-align: left;"><strong>2014-01-15</strong></td>
    <td style="text-align: right;"><strong>0011</strong></td>
  </tr>
</table>
<br>


>>>[2014-2015:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q4: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20150220&stmtType=SOA)

>>>[2014-2015:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q3: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20141121&stmtType=SOA)

>>>[2014-2015:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q2: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20140822&stmtType=SOA)

>>>[2014-2015:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q1: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20140606&stmtType=SOA)




<table style="width:90%; border: 0px; background-color: #96D4D4; height: 5px; margin-left: 30px;">
    <tr style=" padding-top: 0px;">
    <td style="text-align: left;"><strong>2015-01-15</strong></td>
    <td style="text-align: right;"><strong>0013</strong></td>
  </tr>
</table>
<br>


>>>[2015-2016:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q4: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20160219&stmtType=SOA)

>>>[2015-2016:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q3: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20151120&stmtType=SOA)

>>>[2015-2016:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q2: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20150821&stmtType=SOA)

>>>[2015-2016:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q1: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20150605&stmtType=SOA)




<table style="width:90%; border: 0px; background-color: #96D4D4; height: 5px; margin-left: 30px;">
    <tr style=" padding-top: 0px;">
    <td style="text-align: left;"><strong>2016-01-15</strong></td>
    <td style="text-align: right;"><strong>0015</strong></td>
  </tr>
</table>
<br>


>>>[2016-2017&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q4: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20170224&stmtType=SOA)

>>>[2016-2017&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q3: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20161118&stmtType=SOA)

>>>[2016-2017&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q2: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20160826&stmtType=SOA)

>>>[2016-2017&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q1: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20160603&stmtType=SOA)


<table style="width:90%; border: 0px; background-color: #96D4D4; height: 5px; margin-left: 30px;">
    <tr style=" padding-top: 0px;">
    <td style="text-align: left;"><strong>2017-01-15</strong></td>
    <td style="text-align: right;"><strong>0017</strong></td>
 </tr>
</table>
<br>

>>>[2017-2018:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q4: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20180223&stmtType=SOA)

>>>[2017-2018:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q3: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20171117&stmtType=SOA)

>>>[2017-2018:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q2: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20170825&stmtType=SOA)

>>>[2017-2018:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q1: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20170602&stmtType=SOA)

<table style="width:90%; border: 0px; background-color: #96D4D4; height: 5px; margin-left: 30px;">
    <tr style=" padding-top: 0px;">
    <td style="text-align: left;"><strong>2018-01-15</strong></td>
    <td style="text-align: right;"><strong>0019</strong></td>
 </tr>
</table>
<br>

>>>[2018-2019:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q4: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20190201&stmtType=SOA)

>>>[2018-2019:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q4: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20181116&stmtType=SOA)

>>>[2018-2019:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q2: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20180824&stmtType=SOA)

>>>[2018-2019:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q1: NYC](https://a836-mspuvw-dofptsz.nyc.gov/PTSCM/StatementSearch?bbl=1005030011&stmtDate=20180601&stmtType=SOA)

<table style="width:90%; border: 0px; background-color: #96D4D4; height: 5px; margin-left: 30px;">
    <tr style=" padding-top: 0px;">
    <td style="text-align: left;"><strong>2019-01-15</strong></td>
    <td style="text-align: right;"><strong>0021</strong></td>
 </tr>
</table>
<br>

>>>[2019-2020:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q4: NYC](https://a836-edms.nyc.gov/dctm-rest/repositories/dofedmspts/StatementSearch?bbl=1005030011&stmtDate=20200222&stmtType=SOA)

>>>[2019-2020:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q3: NYC](https://a836-edms.nyc.gov/dctm-rest/repositories/dofedmspts/StatementSearch?bbl=1005030011&stmtDate=20191119&stmtType=SOA)

>>>[2019-2020:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q2: NYC](https://a836-edms.nyc.gov/dctm-rest/repositories/dofedmspts/StatementSearch?bbl=1005030011&stmtDate=20190829&stmtType=SOA)

>>>[2019-2020:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q1: NYC](https://a836-edms.nyc.gov/dctm-rest/repositories/dofedmspts/StatementSearch?bbl=1005030011&stmtDate=20190605&stmtType=SOA)


<table style="width:90%; border: 0px; background-color: #96D4D4; height: 5px; margin-left: 30px;">
    <tr style=" padding-top: 0px;">
    <td style="text-align: left;"><strong>2020-01-15</strong></td>
    <td style="text-align: right;"><strong>0025</strong></td>
 </tr>
</table>
<br>

>>>[2020-2021:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q4: NYC](https://a836-edms.nyc.gov/dctm-rest/repositories/dofedmspts/StatementSearch?bbl=1005030011&stmtDate=20210227&stmtType=SOA)

>>>[2020-2021:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q3: NYC](https://a836-edms.nyc.gov/dctm-rest/repositories/dofedmspts/StatementSearch?bbl=1005030011&stmtDate=20201121&stmtType=SOA)

>>>[2020-2021:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q2: NYC](https://a836-edms.nyc.gov/dctm-rest/repositories/dofedmspts/StatementSearch?bbl=1005030011&stmtDate=20200829&stmtType=SOA)

>>>[2020-2021:&nbsp;&nbsp;&nbsp;&nbsp;Tax Bill&nbsp;&nbsp;&nbsp;&nbsp;Q1: NYC](https://a836-edms.nyc.gov/dctm-rest/repositories/dofedmspts/StatementSearch?bbl=1005030011&stmtDate=20200606&stmtType=SOA)



		
	
	113 REAR SULLIVAN STREET, BIN CODE 1077254. . . . . . .. . . . . . . . . . . . . . . . . . . . . . . . . . . [0040]
	- NO CERTIFICATE OF OCCUPANCY 															03-03-2022
	- NO CERTIFICATE OF OCCUPANCY 															08-10-2020 
		
	115 REAR SULLIVAN STREET, BIN CODE 1077254. . . . . . .. . . . . . . . . . . . . . . . . . . . . . . . . . . [0041]	
	- NO CERTIFICATE OF OCCUPANCY 															03-03-2022
	- NO CERTIFICATE OF OCCUPANCY 															08-10-2020
	

	
			

